// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.12.4
// source: cybermetrica.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Cybermetrica_Health_FullMethodName             = "/cybertele.Cybermetrica/Health"
	Cybermetrica_StartParser_FullMethodName        = "/cybertele.Cybermetrica/StartParser"
	Cybermetrica_StopParser_FullMethodName         = "/cybertele.Cybermetrica/StopParser"
	Cybermetrica_GetTelemetryParams_FullMethodName = "/cybertele.Cybermetrica/GetTelemetryParams"
	Cybermetrica_GetTimeline_FullMethodName        = "/cybertele.Cybermetrica/GetTimeline"
)

// CybermetricaClient is the client API for Cybermetrica service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CybermetricaClient interface {
	Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthReply, error)
	StartParser(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ParserStatus, error)
	StopParser(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ParserStatus, error)
	GetTelemetryParams(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TelemertyParams, error)
	GetTimeline(ctx context.Context, in *TimelineRequest, opts ...grpc.CallOption) (*Timeline, error)
}

type cybermetricaClient struct {
	cc grpc.ClientConnInterface
}

func NewCybermetricaClient(cc grpc.ClientConnInterface) CybermetricaClient {
	return &cybermetricaClient{cc}
}

func (c *cybermetricaClient) Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthReply)
	err := c.cc.Invoke(ctx, Cybermetrica_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cybermetricaClient) StartParser(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ParserStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParserStatus)
	err := c.cc.Invoke(ctx, Cybermetrica_StartParser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cybermetricaClient) StopParser(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ParserStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParserStatus)
	err := c.cc.Invoke(ctx, Cybermetrica_StopParser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cybermetricaClient) GetTelemetryParams(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TelemertyParams, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TelemertyParams)
	err := c.cc.Invoke(ctx, Cybermetrica_GetTelemetryParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cybermetricaClient) GetTimeline(ctx context.Context, in *TimelineRequest, opts ...grpc.CallOption) (*Timeline, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Timeline)
	err := c.cc.Invoke(ctx, Cybermetrica_GetTimeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CybermetricaServer is the server API for Cybermetrica service.
// All implementations must embed UnimplementedCybermetricaServer
// for forward compatibility.
type CybermetricaServer interface {
	Health(context.Context, *Empty) (*HealthReply, error)
	StartParser(context.Context, *Empty) (*ParserStatus, error)
	StopParser(context.Context, *Empty) (*ParserStatus, error)
	GetTelemetryParams(context.Context, *Empty) (*TelemertyParams, error)
	GetTimeline(context.Context, *TimelineRequest) (*Timeline, error)
	mustEmbedUnimplementedCybermetricaServer()
}

// UnimplementedCybermetricaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCybermetricaServer struct{}

func (UnimplementedCybermetricaServer) Health(context.Context, *Empty) (*HealthReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedCybermetricaServer) StartParser(context.Context, *Empty) (*ParserStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method StartParser not implemented")
}
func (UnimplementedCybermetricaServer) StopParser(context.Context, *Empty) (*ParserStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method StopParser not implemented")
}
func (UnimplementedCybermetricaServer) GetTelemetryParams(context.Context, *Empty) (*TelemertyParams, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTelemetryParams not implemented")
}
func (UnimplementedCybermetricaServer) GetTimeline(context.Context, *TimelineRequest) (*Timeline, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTimeline not implemented")
}
func (UnimplementedCybermetricaServer) mustEmbedUnimplementedCybermetricaServer() {}
func (UnimplementedCybermetricaServer) testEmbeddedByValue()                      {}

// UnsafeCybermetricaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CybermetricaServer will
// result in compilation errors.
type UnsafeCybermetricaServer interface {
	mustEmbedUnimplementedCybermetricaServer()
}

func RegisterCybermetricaServer(s grpc.ServiceRegistrar, srv CybermetricaServer) {
	// If the following call panics, it indicates UnimplementedCybermetricaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Cybermetrica_ServiceDesc, srv)
}

func _Cybermetrica_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybermetricaServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cybermetrica_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybermetricaServer).Health(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cybermetrica_StartParser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybermetricaServer).StartParser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cybermetrica_StartParser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybermetricaServer).StartParser(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cybermetrica_StopParser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybermetricaServer).StopParser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cybermetrica_StopParser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybermetricaServer).StopParser(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cybermetrica_GetTelemetryParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybermetricaServer).GetTelemetryParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cybermetrica_GetTelemetryParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybermetricaServer).GetTelemetryParams(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cybermetrica_GetTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybermetricaServer).GetTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cybermetrica_GetTimeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybermetricaServer).GetTimeline(ctx, req.(*TimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Cybermetrica_ServiceDesc is the grpc.ServiceDesc for Cybermetrica service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cybermetrica_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cybertele.Cybermetrica",
	HandlerType: (*CybermetricaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _Cybermetrica_Health_Handler,
		},
		{
			MethodName: "StartParser",
			Handler:    _Cybermetrica_StartParser_Handler,
		},
		{
			MethodName: "StopParser",
			Handler:    _Cybermetrica_StopParser_Handler,
		},
		{
			MethodName: "GetTelemetryParams",
			Handler:    _Cybermetrica_GetTelemetryParams_Handler,
		},
		{
			MethodName: "GetTimeline",
			Handler:    _Cybermetrica_GetTimeline_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cybermetrica.proto",
}
