// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: cybermetrica.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MachineStatisticRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            string                 `protobuf:"bytes,1,opt,name=sn,proto3" json:"sn,omitempty"`
	Timezone      int32                  `protobuf:"varint,2,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	From          string                 `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	Graph         string                 `protobuf:"bytes,6,opt,name=graph,proto3" json:"graph,omitempty"`
	Code          float32                `protobuf:"fixed32,7,opt,name=code,proto3" json:"code,omitempty"`
	Period        string                 `protobuf:"bytes,8,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineStatisticRequest) Reset() {
	*x = MachineStatisticRequest{}
	mi := &file_cybermetrica_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineStatisticRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineStatisticRequest) ProtoMessage() {}

func (x *MachineStatisticRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cybermetrica_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineStatisticRequest.ProtoReflect.Descriptor instead.
func (*MachineStatisticRequest) Descriptor() ([]byte, []int) {
	return file_cybermetrica_proto_rawDescGZIP(), []int{0}
}

func (x *MachineStatisticRequest) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *MachineStatisticRequest) GetTimezone() int32 {
	if x != nil {
		return x.Timezone
	}
	return 0
}

func (x *MachineStatisticRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *MachineStatisticRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *MachineStatisticRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *MachineStatisticRequest) GetGraph() string {
	if x != nil {
		return x.Graph
	}
	return ""
}

func (x *MachineStatisticRequest) GetCode() float32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MachineStatisticRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type StatisticEngine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	All           int64                  `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"`
	Idle          int64                  `protobuf:"varint,2,opt,name=idle,proto3" json:"idle,omitempty"`
	Work          int64                  `protobuf:"varint,3,opt,name=work,proto3" json:"work,omitempty"`
	HighRPM       int64                  `protobuf:"varint,4,opt,name=highRPM,proto3" json:"highRPM,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticEngine) Reset() {
	*x = StatisticEngine{}
	mi := &file_cybermetrica_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticEngine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticEngine) ProtoMessage() {}

func (x *StatisticEngine) ProtoReflect() protoreflect.Message {
	mi := &file_cybermetrica_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticEngine.ProtoReflect.Descriptor instead.
func (*StatisticEngine) Descriptor() ([]byte, []int) {
	return file_cybermetrica_proto_rawDescGZIP(), []int{1}
}

func (x *StatisticEngine) GetAll() int64 {
	if x != nil {
		return x.All
	}
	return 0
}

func (x *StatisticEngine) GetIdle() int64 {
	if x != nil {
		return x.Idle
	}
	return 0
}

func (x *StatisticEngine) GetWork() int64 {
	if x != nil {
		return x.Work
	}
	return 0
}

func (x *StatisticEngine) GetHighRPM() int64 {
	if x != nil {
		return x.HighRPM
	}
	return 0
}

type StatisticFuel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consumption   int32                  `protobuf:"varint,1,opt,name=consumption,proto3" json:"consumption,omitempty"`
	DrainVolume   int32                  `protobuf:"varint,2,opt,name=drainVolume,proto3" json:"drainVolume,omitempty"`
	DrainCount    int32                  `protobuf:"varint,3,opt,name=drainCount,proto3" json:"drainCount,omitempty"`
	RefillVolume  int32                  `protobuf:"varint,4,opt,name=refillVolume,proto3" json:"refillVolume,omitempty"`
	RefillCount   int32                  `protobuf:"varint,5,opt,name=refillCount,proto3" json:"refillCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticFuel) Reset() {
	*x = StatisticFuel{}
	mi := &file_cybermetrica_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticFuel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticFuel) ProtoMessage() {}

func (x *StatisticFuel) ProtoReflect() protoreflect.Message {
	mi := &file_cybermetrica_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticFuel.ProtoReflect.Descriptor instead.
func (*StatisticFuel) Descriptor() ([]byte, []int) {
	return file_cybermetrica_proto_rawDescGZIP(), []int{2}
}

func (x *StatisticFuel) GetConsumption() int32 {
	if x != nil {
		return x.Consumption
	}
	return 0
}

func (x *StatisticFuel) GetDrainVolume() int32 {
	if x != nil {
		return x.DrainVolume
	}
	return 0
}

func (x *StatisticFuel) GetDrainCount() int32 {
	if x != nil {
		return x.DrainCount
	}
	return 0
}

func (x *StatisticFuel) GetRefillVolume() int32 {
	if x != nil {
		return x.RefillVolume
	}
	return 0
}

func (x *StatisticFuel) GetRefillCount() int32 {
	if x != nil {
		return x.RefillCount
	}
	return 0
}

type StatisticPeriodItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Workhours     float32                `protobuf:"fixed32,2,opt,name=workhours,proto3" json:"workhours,omitempty"`
	Engine        *StatisticEngine       `protobuf:"bytes,3,opt,name=engine,proto3" json:"engine,omitempty"`
	Fuel          *StatisticFuel         `protobuf:"bytes,4,opt,name=fuel,proto3" json:"fuel,omitempty"`
	Job           int64                  `protobuf:"varint,5,opt,name=job,proto3" json:"job,omitempty"`
	Connection    int64                  `protobuf:"varint,6,opt,name=connection,proto3" json:"connection,omitempty"`
	ErrorsCount   int32                  `protobuf:"varint,7,opt,name=errorsCount,proto3" json:"errorsCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticPeriodItem) Reset() {
	*x = StatisticPeriodItem{}
	mi := &file_cybermetrica_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticPeriodItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticPeriodItem) ProtoMessage() {}

func (x *StatisticPeriodItem) ProtoReflect() protoreflect.Message {
	mi := &file_cybermetrica_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticPeriodItem.ProtoReflect.Descriptor instead.
func (*StatisticPeriodItem) Descriptor() ([]byte, []int) {
	return file_cybermetrica_proto_rawDescGZIP(), []int{3}
}

func (x *StatisticPeriodItem) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *StatisticPeriodItem) GetWorkhours() float32 {
	if x != nil {
		return x.Workhours
	}
	return 0
}

func (x *StatisticPeriodItem) GetEngine() *StatisticEngine {
	if x != nil {
		return x.Engine
	}
	return nil
}

func (x *StatisticPeriodItem) GetFuel() *StatisticFuel {
	if x != nil {
		return x.Fuel
	}
	return nil
}

func (x *StatisticPeriodItem) GetJob() int64 {
	if x != nil {
		return x.Job
	}
	return 0
}

func (x *StatisticPeriodItem) GetConnection() int64 {
	if x != nil {
		return x.Connection
	}
	return 0
}

func (x *StatisticPeriodItem) GetErrorsCount() int32 {
	if x != nil {
		return x.ErrorsCount
	}
	return 0
}

type StatisticPeriod struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Sn             string                 `protobuf:"bytes,1,opt,name=sn,proto3" json:"sn,omitempty"`
	Timezone       int32                  `protobuf:"varint,2,opt,name=timezone,proto3" json:"timezone,omitempty"`
	From           string                 `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To             string                 `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Period         string                 `protobuf:"bytes,5,opt,name=period,proto3" json:"period,omitempty"`
	Step           string                 `protobuf:"bytes,6,opt,name=step,proto3" json:"step,omitempty"`
	Data           []*StatisticPeriodItem `protobuf:"bytes,7,rep,name=data,proto3" json:"data,omitempty"`
	WorkhoursStart float32                `protobuf:"fixed32,8,opt,name=workhoursStart,proto3" json:"workhoursStart,omitempty"`
	WorkhoursEnd   float32                `protobuf:"fixed32,9,opt,name=workhoursEnd,proto3" json:"workhoursEnd,omitempty"`
	Fuel           *StatisticFuel         `protobuf:"bytes,10,opt,name=fuel,proto3" json:"fuel,omitempty"`
	ErrorsCount    int32                  `protobuf:"varint,11,opt,name=errorsCount,proto3" json:"errorsCount,omitempty"`
	Connection     int64                  `protobuf:"varint,12,opt,name=connection,proto3" json:"connection,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatisticPeriod) Reset() {
	*x = StatisticPeriod{}
	mi := &file_cybermetrica_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticPeriod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticPeriod) ProtoMessage() {}

func (x *StatisticPeriod) ProtoReflect() protoreflect.Message {
	mi := &file_cybermetrica_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticPeriod.ProtoReflect.Descriptor instead.
func (*StatisticPeriod) Descriptor() ([]byte, []int) {
	return file_cybermetrica_proto_rawDescGZIP(), []int{4}
}

func (x *StatisticPeriod) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *StatisticPeriod) GetTimezone() int32 {
	if x != nil {
		return x.Timezone
	}
	return 0
}

func (x *StatisticPeriod) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *StatisticPeriod) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *StatisticPeriod) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *StatisticPeriod) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *StatisticPeriod) GetData() []*StatisticPeriodItem {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StatisticPeriod) GetWorkhoursStart() float32 {
	if x != nil {
		return x.WorkhoursStart
	}
	return 0
}

func (x *StatisticPeriod) GetWorkhoursEnd() float32 {
	if x != nil {
		return x.WorkhoursEnd
	}
	return 0
}

func (x *StatisticPeriod) GetFuel() *StatisticFuel {
	if x != nil {
		return x.Fuel
	}
	return nil
}

func (x *StatisticPeriod) GetErrorsCount() int32 {
	if x != nil {
		return x.ErrorsCount
	}
	return 0
}

func (x *StatisticPeriod) GetConnection() int64 {
	if x != nil {
		return x.Connection
	}
	return 0
}

type TelemertyParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        []*TelemertyParam      `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemertyParams) Reset() {
	*x = TelemertyParams{}
	mi := &file_cybermetrica_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemertyParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemertyParams) ProtoMessage() {}

func (x *TelemertyParams) ProtoReflect() protoreflect.Message {
	mi := &file_cybermetrica_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemertyParams.ProtoReflect.Descriptor instead.
func (*TelemertyParams) Descriptor() ([]byte, []int) {
	return file_cybermetrica_proto_rawDescGZIP(), []int{5}
}

func (x *TelemertyParams) GetParams() []*TelemertyParam {
	if x != nil {
		return x.Params
	}
	return nil
}

type TelemertyParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Units         string                 `protobuf:"bytes,3,opt,name=units,proto3" json:"units,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemertyParam) Reset() {
	*x = TelemertyParam{}
	mi := &file_cybermetrica_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemertyParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemertyParam) ProtoMessage() {}

func (x *TelemertyParam) ProtoReflect() protoreflect.Message {
	mi := &file_cybermetrica_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemertyParam.ProtoReflect.Descriptor instead.
func (*TelemertyParam) Descriptor() ([]byte, []int) {
	return file_cybermetrica_proto_rawDescGZIP(), []int{6}
}

func (x *TelemertyParam) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *TelemertyParam) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *TelemertyParam) GetUnits() string {
	if x != nil {
		return x.Units
	}
	return ""
}

func (x *TelemertyParam) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type TimelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            string                 `protobuf:"bytes,1,opt,name=sn,proto3" json:"sn,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Tz            int32                  `protobuf:"varint,3,opt,name=tz,proto3" json:"tz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelineRequest) Reset() {
	*x = TimelineRequest{}
	mi := &file_cybermetrica_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineRequest) ProtoMessage() {}

func (x *TimelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cybermetrica_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineRequest.ProtoReflect.Descriptor instead.
func (*TimelineRequest) Descriptor() ([]byte, []int) {
	return file_cybermetrica_proto_rawDescGZIP(), []int{7}
}

func (x *TimelineRequest) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *TimelineRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *TimelineRequest) GetTz() int32 {
	if x != nil {
		return x.Tz
	}
	return 0
}

type DataValuesRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataValuesRow) Reset() {
	*x = DataValuesRow{}
	mi := &file_cybermetrica_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataValuesRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataValuesRow) ProtoMessage() {}

func (x *DataValuesRow) ProtoReflect() protoreflect.Message {
	mi := &file_cybermetrica_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataValuesRow.ProtoReflect.Descriptor instead.
func (*DataValuesRow) Descriptor() ([]byte, []int) {
	return file_cybermetrica_proto_rawDescGZIP(), []int{8}
}

func (x *DataValuesRow) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type ConnectionDataBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Finished      bool                   `protobuf:"varint,2,opt,name=finished,proto3" json:"finished,omitempty"`
	DataValues    []*DataValuesRow       `protobuf:"bytes,3,rep,name=dataValues,proto3" json:"dataValues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionDataBlock) Reset() {
	*x = ConnectionDataBlock{}
	mi := &file_cybermetrica_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionDataBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionDataBlock) ProtoMessage() {}

func (x *ConnectionDataBlock) ProtoReflect() protoreflect.Message {
	mi := &file_cybermetrica_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionDataBlock.ProtoReflect.Descriptor instead.
func (*ConnectionDataBlock) Descriptor() ([]byte, []int) {
	return file_cybermetrica_proto_rawDescGZIP(), []int{9}
}

func (x *ConnectionDataBlock) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConnectionDataBlock) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *ConnectionDataBlock) GetDataValues() []*DataValuesRow {
	if x != nil {
		return x.DataValues
	}
	return nil
}

type EventBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         int64                  `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End           int64                  `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	Value         float32                `protobuf:"fixed32,3,opt,name=value,proto3" json:"value,omitempty"`
	Id            int64                  `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventBlock) Reset() {
	*x = EventBlock{}
	mi := &file_cybermetrica_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBlock) ProtoMessage() {}

func (x *EventBlock) ProtoReflect() protoreflect.Message {
	mi := &file_cybermetrica_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBlock.ProtoReflect.Descriptor instead.
func (*EventBlock) Descriptor() ([]byte, []int) {
	return file_cybermetrica_proto_rawDescGZIP(), []int{10}
}

func (x *EventBlock) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *EventBlock) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *EventBlock) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *EventBlock) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Timeline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            string                 `protobuf:"bytes,1,opt,name=sn,proto3" json:"sn,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Tz            int32                  `protobuf:"varint,3,opt,name=tz,proto3" json:"tz,omitempty"`
	StartTimeUnix int64                  `protobuf:"varint,4,opt,name=startTimeUnix,proto3" json:"startTimeUnix,omitempty"`
	Params        []string               `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty"`
	Connections   []*EventBlock          `protobuf:"bytes,6,rep,name=connections,proto3" json:"connections,omitempty"`
	Engines       []*EventBlock          `protobuf:"bytes,7,rep,name=engines,proto3" json:"engines,omitempty"`
	Jobs          []*EventBlock          `protobuf:"bytes,8,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Errors        []*EventBlock          `protobuf:"bytes,9,rep,name=errors,proto3" json:"errors,omitempty"`
	Data          []*ConnectionDataBlock `protobuf:"bytes,10,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timeline) Reset() {
	*x = Timeline{}
	mi := &file_cybermetrica_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timeline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timeline) ProtoMessage() {}

func (x *Timeline) ProtoReflect() protoreflect.Message {
	mi := &file_cybermetrica_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timeline.ProtoReflect.Descriptor instead.
func (*Timeline) Descriptor() ([]byte, []int) {
	return file_cybermetrica_proto_rawDescGZIP(), []int{11}
}

func (x *Timeline) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *Timeline) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Timeline) GetTz() int32 {
	if x != nil {
		return x.Tz
	}
	return 0
}

func (x *Timeline) GetStartTimeUnix() int64 {
	if x != nil {
		return x.StartTimeUnix
	}
	return 0
}

func (x *Timeline) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Timeline) GetConnections() []*EventBlock {
	if x != nil {
		return x.Connections
	}
	return nil
}

func (x *Timeline) GetEngines() []*EventBlock {
	if x != nil {
		return x.Engines
	}
	return nil
}

func (x *Timeline) GetJobs() []*EventBlock {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *Timeline) GetErrors() []*EventBlock {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *Timeline) GetData() []*ConnectionDataBlock {
	if x != nil {
		return x.Data
	}
	return nil
}

type Events struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Events) Reset() {
	*x = Events{}
	mi := &file_cybermetrica_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Events) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Events) ProtoMessage() {}

func (x *Events) ProtoReflect() protoreflect.Message {
	mi := &file_cybermetrica_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Events.ProtoReflect.Descriptor instead.
func (*Events) Descriptor() ([]byte, []int) {
	return file_cybermetrica_proto_rawDescGZIP(), []int{12}
}

func (x *Events) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StartTime     string                 `protobuf:"bytes,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime       string                 `protobuf:"bytes,3,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Status        Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=cybertele.Status" json:"status,omitempty"`
	Code          float32                `protobuf:"fixed32,5,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_cybermetrica_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_cybermetrica_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_cybermetrica_proto_rawDescGZIP(), []int{13}
}

func (x *Event) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Event) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Event) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *Event) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNKNOWN
}

func (x *Event) GetCode() float32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_cybermetrica_proto protoreflect.FileDescriptor

const file_cybermetrica_proto_rawDesc = "" +
	"\n" +
	"\x12cybermetrica.proto\x12\tcybertele\x1a\vcyber.proto\"\xbf\x01\n" +
	"\x17MachineStatisticRequest\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\tR\x02sn\x12\x1a\n" +
	"\btimezone\x18\x02 \x01(\x05R\btimezone\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x12\n" +
	"\x04from\x18\x04 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x05 \x01(\tR\x02to\x12\x14\n" +
	"\x05graph\x18\x06 \x01(\tR\x05graph\x12\x12\n" +
	"\x04code\x18\a \x01(\x02R\x04code\x12\x16\n" +
	"\x06period\x18\b \x01(\tR\x06period\"e\n" +
	"\x0fStatisticEngine\x12\x10\n" +
	"\x03all\x18\x01 \x01(\x03R\x03all\x12\x12\n" +
	"\x04idle\x18\x02 \x01(\x03R\x04idle\x12\x12\n" +
	"\x04work\x18\x03 \x01(\x03R\x04work\x12\x18\n" +
	"\ahighRPM\x18\x04 \x01(\x03R\ahighRPM\"\xb9\x01\n" +
	"\rStatisticFuel\x12 \n" +
	"\vconsumption\x18\x01 \x01(\x05R\vconsumption\x12 \n" +
	"\vdrainVolume\x18\x02 \x01(\x05R\vdrainVolume\x12\x1e\n" +
	"\n" +
	"drainCount\x18\x03 \x01(\x05R\n" +
	"drainCount\x12\"\n" +
	"\frefillVolume\x18\x04 \x01(\x05R\frefillVolume\x12 \n" +
	"\vrefillCount\x18\x05 \x01(\x05R\vrefillCount\"\xff\x01\n" +
	"\x13StatisticPeriodItem\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x1c\n" +
	"\tworkhours\x18\x02 \x01(\x02R\tworkhours\x122\n" +
	"\x06engine\x18\x03 \x01(\v2\x1a.cybertele.StatisticEngineR\x06engine\x12,\n" +
	"\x04fuel\x18\x04 \x01(\v2\x18.cybertele.StatisticFuelR\x04fuel\x12\x10\n" +
	"\x03job\x18\x05 \x01(\x03R\x03job\x12\x1e\n" +
	"\n" +
	"connection\x18\x06 \x01(\x03R\n" +
	"connection\x12 \n" +
	"\verrorsCount\x18\a \x01(\x05R\verrorsCount\"\xfd\x02\n" +
	"\x0fStatisticPeriod\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\tR\x02sn\x12\x1a\n" +
	"\btimezone\x18\x02 \x01(\x05R\btimezone\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\tR\x02to\x12\x16\n" +
	"\x06period\x18\x05 \x01(\tR\x06period\x12\x12\n" +
	"\x04step\x18\x06 \x01(\tR\x04step\x122\n" +
	"\x04data\x18\a \x03(\v2\x1e.cybertele.StatisticPeriodItemR\x04data\x12&\n" +
	"\x0eworkhoursStart\x18\b \x01(\x02R\x0eworkhoursStart\x12\"\n" +
	"\fworkhoursEnd\x18\t \x01(\x02R\fworkhoursEnd\x12,\n" +
	"\x04fuel\x18\n" +
	" \x01(\v2\x18.cybertele.StatisticFuelR\x04fuel\x12 \n" +
	"\verrorsCount\x18\v \x01(\x05R\verrorsCount\x12\x1e\n" +
	"\n" +
	"connection\x18\f \x01(\x03R\n" +
	"connection\"D\n" +
	"\x0fTelemertyParams\x121\n" +
	"\x06params\x18\x01 \x03(\v2\x19.cybertele.TelemertyParamR\x06params\"r\n" +
	"\x0eTelemertyParam\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x14\n" +
	"\x05units\x18\x03 \x01(\tR\x05units\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"E\n" +
	"\x0fTimelineRequest\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\tR\x02sn\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x0e\n" +
	"\x02tz\x18\x03 \x01(\x05R\x02tz\"'\n" +
	"\rDataValuesRow\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"{\n" +
	"\x13ConnectionDataBlock\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bfinished\x18\x02 \x01(\bR\bfinished\x128\n" +
	"\n" +
	"dataValues\x18\x03 \x03(\v2\x18.cybertele.DataValuesRowR\n" +
	"dataValues\"Z\n" +
	"\n" +
	"EventBlock\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x03R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x03R\x03end\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x02R\x05value\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\x03R\x02id\"\xf4\x02\n" +
	"\bTimeline\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\tR\x02sn\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x0e\n" +
	"\x02tz\x18\x03 \x01(\x05R\x02tz\x12$\n" +
	"\rstartTimeUnix\x18\x04 \x01(\x03R\rstartTimeUnix\x12\x16\n" +
	"\x06params\x18\x05 \x03(\tR\x06params\x127\n" +
	"\vconnections\x18\x06 \x03(\v2\x15.cybertele.EventBlockR\vconnections\x12/\n" +
	"\aengines\x18\a \x03(\v2\x15.cybertele.EventBlockR\aengines\x12)\n" +
	"\x04jobs\x18\b \x03(\v2\x15.cybertele.EventBlockR\x04jobs\x12-\n" +
	"\x06errors\x18\t \x03(\v2\x15.cybertele.EventBlockR\x06errors\x122\n" +
	"\x04data\x18\n" +
	" \x03(\v2\x1e.cybertele.ConnectionDataBlockR\x04data\"2\n" +
	"\x06Events\x12(\n" +
	"\x06events\x18\x01 \x03(\v2\x10.cybertele.EventR\x06events\"\xca\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\tstartTime\x18\x02 \x01(\tR\tstartTime\x12\x18\n" +
	"\aendTime\x18\x03 \x01(\tR\aendTime\x12)\n" +
	"\x06status\x18\x04 \x01(\x0e2\x11.cybertele.StatusR\x06status\x12\x12\n" +
	"\x04code\x18\x05 \x01(\x02R\x04code\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription2\xf7\x04\n" +
	"\fCybermetrica\x124\n" +
	"\x06Health\x12\x10.cybertele.Empty\x1a\x16.cybertele.HealthReply\"\x00\x12:\n" +
	"\vStartParser\x12\x10.cybertele.Empty\x1a\x17.cybertele.ParserStatus\"\x00\x129\n" +
	"\n" +
	"StopParser\x12\x10.cybertele.Empty\x1a\x17.cybertele.ParserStatus\"\x00\x12Z\n" +
	"\x16MachineStatisticPeriod\x12\".cybertele.MachineStatisticRequest\x1a\x1a.cybertele.StatisticPeriod\"\x00\x12D\n" +
	"\x12GetTelemetryParams\x12\x10.cybertele.Empty\x1a\x1a.cybertele.TelemertyParams\"\x00\x12K\n" +
	"\x14CreateTelemetryParam\x12\x19.cybertele.TelemertyParam\x1a\x16.cybertele.StatusReply\"\x00\x12K\n" +
	"\x14UpdateTelemetryParam\x12\x19.cybertele.TelemertyParam\x1a\x16.cybertele.StatusReply\"\x00\x12@\n" +
	"\vGetTimeline\x12\x1a.cybertele.TimelineRequest\x1a\x13.cybertele.Timeline\"\x00\x12<\n" +
	"\tGetEvents\x12\x1a.cybertele.TimelineRequest\x1a\x11.cybertele.Events\"\x00B\tZ\a./protob\x06proto3"

var (
	file_cybermetrica_proto_rawDescOnce sync.Once
	file_cybermetrica_proto_rawDescData []byte
)

func file_cybermetrica_proto_rawDescGZIP() []byte {
	file_cybermetrica_proto_rawDescOnce.Do(func() {
		file_cybermetrica_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cybermetrica_proto_rawDesc), len(file_cybermetrica_proto_rawDesc)))
	})
	return file_cybermetrica_proto_rawDescData
}

var file_cybermetrica_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_cybermetrica_proto_goTypes = []any{
	(*MachineStatisticRequest)(nil), // 0: cybertele.MachineStatisticRequest
	(*StatisticEngine)(nil),         // 1: cybertele.StatisticEngine
	(*StatisticFuel)(nil),           // 2: cybertele.StatisticFuel
	(*StatisticPeriodItem)(nil),     // 3: cybertele.StatisticPeriodItem
	(*StatisticPeriod)(nil),         // 4: cybertele.StatisticPeriod
	(*TelemertyParams)(nil),         // 5: cybertele.TelemertyParams
	(*TelemertyParam)(nil),          // 6: cybertele.TelemertyParam
	(*TimelineRequest)(nil),         // 7: cybertele.TimelineRequest
	(*DataValuesRow)(nil),           // 8: cybertele.DataValuesRow
	(*ConnectionDataBlock)(nil),     // 9: cybertele.ConnectionDataBlock
	(*EventBlock)(nil),              // 10: cybertele.EventBlock
	(*Timeline)(nil),                // 11: cybertele.Timeline
	(*Events)(nil),                  // 12: cybertele.Events
	(*Event)(nil),                   // 13: cybertele.Event
	(Status)(0),                     // 14: cybertele.Status
	(*Empty)(nil),                   // 15: cybertele.Empty
	(*HealthReply)(nil),             // 16: cybertele.HealthReply
	(*ParserStatus)(nil),            // 17: cybertele.ParserStatus
	(*StatusReply)(nil),             // 18: cybertele.StatusReply
}
var file_cybermetrica_proto_depIdxs = []int32{
	1,  // 0: cybertele.StatisticPeriodItem.engine:type_name -> cybertele.StatisticEngine
	2,  // 1: cybertele.StatisticPeriodItem.fuel:type_name -> cybertele.StatisticFuel
	3,  // 2: cybertele.StatisticPeriod.data:type_name -> cybertele.StatisticPeriodItem
	2,  // 3: cybertele.StatisticPeriod.fuel:type_name -> cybertele.StatisticFuel
	6,  // 4: cybertele.TelemertyParams.params:type_name -> cybertele.TelemertyParam
	8,  // 5: cybertele.ConnectionDataBlock.dataValues:type_name -> cybertele.DataValuesRow
	10, // 6: cybertele.Timeline.connections:type_name -> cybertele.EventBlock
	10, // 7: cybertele.Timeline.engines:type_name -> cybertele.EventBlock
	10, // 8: cybertele.Timeline.jobs:type_name -> cybertele.EventBlock
	10, // 9: cybertele.Timeline.errors:type_name -> cybertele.EventBlock
	9,  // 10: cybertele.Timeline.data:type_name -> cybertele.ConnectionDataBlock
	13, // 11: cybertele.Events.events:type_name -> cybertele.Event
	14, // 12: cybertele.Event.status:type_name -> cybertele.Status
	15, // 13: cybertele.Cybermetrica.Health:input_type -> cybertele.Empty
	15, // 14: cybertele.Cybermetrica.StartParser:input_type -> cybertele.Empty
	15, // 15: cybertele.Cybermetrica.StopParser:input_type -> cybertele.Empty
	0,  // 16: cybertele.Cybermetrica.MachineStatisticPeriod:input_type -> cybertele.MachineStatisticRequest
	15, // 17: cybertele.Cybermetrica.GetTelemetryParams:input_type -> cybertele.Empty
	6,  // 18: cybertele.Cybermetrica.CreateTelemetryParam:input_type -> cybertele.TelemertyParam
	6,  // 19: cybertele.Cybermetrica.UpdateTelemetryParam:input_type -> cybertele.TelemertyParam
	7,  // 20: cybertele.Cybermetrica.GetTimeline:input_type -> cybertele.TimelineRequest
	7,  // 21: cybertele.Cybermetrica.GetEvents:input_type -> cybertele.TimelineRequest
	16, // 22: cybertele.Cybermetrica.Health:output_type -> cybertele.HealthReply
	17, // 23: cybertele.Cybermetrica.StartParser:output_type -> cybertele.ParserStatus
	17, // 24: cybertele.Cybermetrica.StopParser:output_type -> cybertele.ParserStatus
	4,  // 25: cybertele.Cybermetrica.MachineStatisticPeriod:output_type -> cybertele.StatisticPeriod
	5,  // 26: cybertele.Cybermetrica.GetTelemetryParams:output_type -> cybertele.TelemertyParams
	18, // 27: cybertele.Cybermetrica.CreateTelemetryParam:output_type -> cybertele.StatusReply
	18, // 28: cybertele.Cybermetrica.UpdateTelemetryParam:output_type -> cybertele.StatusReply
	11, // 29: cybertele.Cybermetrica.GetTimeline:output_type -> cybertele.Timeline
	12, // 30: cybertele.Cybermetrica.GetEvents:output_type -> cybertele.Events
	22, // [22:31] is the sub-list for method output_type
	13, // [13:22] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_cybermetrica_proto_init() }
func file_cybermetrica_proto_init() {
	if File_cybermetrica_proto != nil {
		return
	}
	file_cyber_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cybermetrica_proto_rawDesc), len(file_cybermetrica_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cybermetrica_proto_goTypes,
		DependencyIndexes: file_cybermetrica_proto_depIdxs,
		MessageInfos:      file_cybermetrica_proto_msgTypes,
	}.Build()
	File_cybermetrica_proto = out.File
	file_cybermetrica_proto_goTypes = nil
	file_cybermetrica_proto_depIdxs = nil
}
