// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: cyberfuel.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_cyberfuel_proto protoreflect.FileDescriptor

const file_cyberfuel_proto_rawDesc = "" +
	"\n" +
	"\x0fcyberfuel.proto\x12\tcybertele\x1a\vcyber.proto2}\n" +
	"\tCyberfuel\x124\n" +
	"\x06Health\x12\x10.cybertele.Empty\x1a\x16.cybertele.HealthReply\"\x00\x12:\n" +
	"\n" +
	"CalcEvents\x12\x15.cybertele.DataPoints\x1a\x13.cybertele.Segments\"\x00B\tZ\a./protob\x06proto3"

var file_cyberfuel_proto_goTypes = []any{
	(*Empty)(nil),       // 0: cybertele.Empty
	(*DataPoints)(nil),  // 1: cybertele.DataPoints
	(*HealthReply)(nil), // 2: cybertele.HealthReply
	(*Segments)(nil),    // 3: cybertele.Segments
}
var file_cyberfuel_proto_depIdxs = []int32{
	0, // 0: cybertele.Cyberfuel.Health:input_type -> cybertele.Empty
	1, // 1: cybertele.Cyberfuel.CalcEvents:input_type -> cybertele.DataPoints
	2, // 2: cybertele.Cyberfuel.Health:output_type -> cybertele.HealthReply
	3, // 3: cybertele.Cyberfuel.CalcEvents:output_type -> cybertele.Segments
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cyberfuel_proto_init() }
func file_cyberfuel_proto_init() {
	if File_cyberfuel_proto != nil {
		return
	}
	file_cyber_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cyberfuel_proto_rawDesc), len(file_cyberfuel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cyberfuel_proto_goTypes,
		DependencyIndexes: file_cyberfuel_proto_depIdxs,
	}.Build()
	File_cyberfuel_proto = out.File
	file_cyberfuel_proto_goTypes = nil
	file_cyberfuel_proto_depIdxs = nil
}
