// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: cyber.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status — статус компонента системы.
// При сериализации в JSON используется строковое представление (UNKNOWN, ACTIVE, INACTIVE, OK, ERROR, WARNING).
// Для корректной JSON-сериализации используйте protojson с UseEnumNumbers=false
// или кастомный MarshalJSON из пакета proto.
type Status int32

const (
	// UNKNOWN — статус не определён
	Status_UNKNOWN Status = 0
	// ACTIVE — компонент активен
	Status_ACTIVE Status = 1
	// INACTIVE — компонент неактивен
	Status_INACTIVE Status = 2
	// OK — компонент работает нормально
	Status_OK Status = 3
	// ERROR — ошибка компонента
	Status_ERROR Status = 4
	// WARNING — предупреждение
	Status_WARNING Status = 5
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "ACTIVE",
		2: "INACTIVE",
		3: "OK",
		4: "ERROR",
		5: "WARNING",
	}
	Status_value = map[string]int32{
		"UNKNOWN":  0,
		"ACTIVE":   1,
		"INACTIVE": 2,
		"OK":       3,
		"ERROR":    4,
		"WARNING":  5,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_cyber_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_cyber_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_cyber_proto_rawDescGZIP(), []int{0}
}

type StatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=cybertele.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReply) Reset() {
	*x = StatusReply{}
	mi := &file_cyber_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReply) ProtoMessage() {}

func (x *StatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_cyber_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReply.ProtoReflect.Descriptor instead.
func (*StatusReply) Descriptor() ([]byte, []int) {
	return file_cyber_proto_rawDescGZIP(), []int{0}
}

func (x *StatusReply) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNKNOWN
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_cyber_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_cyber_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_cyber_proto_rawDescGZIP(), []int{1}
}

type Disk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	All           float32                `protobuf:"fixed32,1,opt,name=all,proto3" json:"all,omitempty"`
	Used          float32                `protobuf:"fixed32,2,opt,name=used,proto3" json:"used,omitempty"`
	Free          float32                `protobuf:"fixed32,3,opt,name=free,proto3" json:"free,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disk) Reset() {
	*x = Disk{}
	mi := &file_cyber_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disk) ProtoMessage() {}

func (x *Disk) ProtoReflect() protoreflect.Message {
	mi := &file_cyber_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disk.ProtoReflect.Descriptor instead.
func (*Disk) Descriptor() ([]byte, []int) {
	return file_cyber_proto_rawDescGZIP(), []int{2}
}

func (x *Disk) GetAll() float32 {
	if x != nil {
		return x.All
	}
	return 0
}

func (x *Disk) GetUsed() float32 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *Disk) GetFree() float32 {
	if x != nil {
		return x.Free
	}
	return 0
}

type HealthReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Postgres      Status                 `protobuf:"varint,1,opt,name=postgres,proto3,enum=cybertele.Status" json:"postgres,omitempty"`
	Mongo         Status                 `protobuf:"varint,2,opt,name=mongo,proto3,enum=cybertele.Status" json:"mongo,omitempty"`
	Parser        Status                 `protobuf:"varint,3,opt,name=parser,proto3,enum=cybertele.Status" json:"parser,omitempty"`
	Disk          *Disk                  `protobuf:"bytes,4,opt,name=disk,proto3" json:"disk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthReply) Reset() {
	*x = HealthReply{}
	mi := &file_cyber_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReply) ProtoMessage() {}

func (x *HealthReply) ProtoReflect() protoreflect.Message {
	mi := &file_cyber_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReply.ProtoReflect.Descriptor instead.
func (*HealthReply) Descriptor() ([]byte, []int) {
	return file_cyber_proto_rawDescGZIP(), []int{3}
}

func (x *HealthReply) GetPostgres() Status {
	if x != nil {
		return x.Postgres
	}
	return Status_UNKNOWN
}

func (x *HealthReply) GetMongo() Status {
	if x != nil {
		return x.Mongo
	}
	return Status_UNKNOWN
}

func (x *HealthReply) GetParser() Status {
	if x != nil {
		return x.Parser
	}
	return Status_UNKNOWN
}

func (x *HealthReply) GetDisk() *Disk {
	if x != nil {
		return x.Disk
	}
	return nil
}

type ParserStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parser        Status                 `protobuf:"varint,1,opt,name=parser,proto3,enum=cybertele.Status" json:"parser,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParserStatus) Reset() {
	*x = ParserStatus{}
	mi := &file_cyber_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParserStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParserStatus) ProtoMessage() {}

func (x *ParserStatus) ProtoReflect() protoreflect.Message {
	mi := &file_cyber_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParserStatus.ProtoReflect.Descriptor instead.
func (*ParserStatus) Descriptor() ([]byte, []int) {
	return file_cyber_proto_rawDescGZIP(), []int{4}
}

func (x *ParserStatus) GetParser() Status {
	if x != nil {
		return x.Parser
	}
	return Status_UNKNOWN
}

func (x *ParserStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Sn            string                 `protobuf:"bytes,3,opt,name=sn,proto3" json:"sn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_cyber_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cyber_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_cyber_proto_rawDescGZIP(), []int{5}
}

func (x *PageRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PageRequest) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_cyber_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_cyber_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_cyber_proto_rawDescGZIP(), []int{6}
}

func (x *Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Pagination) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Machine struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Sn             string                 `protobuf:"bytes,1,opt,name=sn,proto3" json:"sn,omitempty"`
	Model          string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Sync           bool                   `protobuf:"varint,3,opt,name=sync,proto3" json:"sync,omitempty"`
	GenerationId   int32                  `protobuf:"varint,4,opt,name=generationId,proto3" json:"generationId,omitempty"`
	ClassId        int32                  `protobuf:"varint,5,opt,name=classId,proto3" json:"classId,omitempty"`
	ClassName      string                 `protobuf:"bytes,6,opt,name=className,proto3" json:"className,omitempty"`
	GenerationName string                 `protobuf:"bytes,7,opt,name=generationName,proto3" json:"generationName,omitempty"`
	ModelId        int32                  `protobuf:"varint,8,opt,name=modelId,proto3" json:"modelId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Machine) Reset() {
	*x = Machine{}
	mi := &file_cyber_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Machine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Machine) ProtoMessage() {}

func (x *Machine) ProtoReflect() protoreflect.Message {
	mi := &file_cyber_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Machine.ProtoReflect.Descriptor instead.
func (*Machine) Descriptor() ([]byte, []int) {
	return file_cyber_proto_rawDescGZIP(), []int{7}
}

func (x *Machine) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *Machine) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Machine) GetSync() bool {
	if x != nil {
		return x.Sync
	}
	return false
}

func (x *Machine) GetGenerationId() int32 {
	if x != nil {
		return x.GenerationId
	}
	return 0
}

func (x *Machine) GetClassId() int32 {
	if x != nil {
		return x.ClassId
	}
	return 0
}

func (x *Machine) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *Machine) GetGenerationName() string {
	if x != nil {
		return x.GenerationName
	}
	return ""
}

func (x *Machine) GetModelId() int32 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

type Machines struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Machines      []*Machine             `protobuf:"bytes,1,rep,name=machines,proto3" json:"machines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Machines) Reset() {
	*x = Machines{}
	mi := &file_cyber_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Machines) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Machines) ProtoMessage() {}

func (x *Machines) ProtoReflect() protoreflect.Message {
	mi := &file_cyber_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Machines.ProtoReflect.Descriptor instead.
func (*Machines) Descriptor() ([]byte, []int) {
	return file_cyber_proto_rawDescGZIP(), []int{8}
}

func (x *Machines) GetMachines() []*Machine {
	if x != nil {
		return x.Machines
	}
	return nil
}

type DataType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Meaning       string                 `protobuf:"bytes,3,opt,name=meaning,proto3" json:"meaning,omitempty"`
	Required      bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	Group         string                 `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataType) Reset() {
	*x = DataType{}
	mi := &file_cyber_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType) ProtoMessage() {}

func (x *DataType) ProtoReflect() protoreflect.Message {
	mi := &file_cyber_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType.ProtoReflect.Descriptor instead.
func (*DataType) Descriptor() ([]byte, []int) {
	return file_cyber_proto_rawDescGZIP(), []int{9}
}

func (x *DataType) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DataType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataType) GetMeaning() string {
	if x != nil {
		return x.Meaning
	}
	return ""
}

func (x *DataType) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *DataType) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type DataTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*DataType            `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataTypes) Reset() {
	*x = DataTypes{}
	mi := &file_cyber_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataTypes) ProtoMessage() {}

func (x *DataTypes) ProtoReflect() protoreflect.Message {
	mi := &file_cyber_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataTypes.ProtoReflect.Descriptor instead.
func (*DataTypes) Descriptor() ([]byte, []int) {
	return file_cyber_proto_rawDescGZIP(), []int{10}
}

func (x *DataTypes) GetData() []*DataType {
	if x != nil {
		return x.Data
	}
	return nil
}

type ModelDataTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	DataTypes     []*DataType            `protobuf:"bytes,2,rep,name=dataTypes,proto3" json:"dataTypes,omitempty"`
	ModelId       int32                  `protobuf:"varint,3,opt,name=modelId,proto3" json:"modelId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelDataTypes) Reset() {
	*x = ModelDataTypes{}
	mi := &file_cyber_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelDataTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelDataTypes) ProtoMessage() {}

func (x *ModelDataTypes) ProtoReflect() protoreflect.Message {
	mi := &file_cyber_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelDataTypes.ProtoReflect.Descriptor instead.
func (*ModelDataTypes) Descriptor() ([]byte, []int) {
	return file_cyber_proto_rawDescGZIP(), []int{11}
}

func (x *ModelDataTypes) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ModelDataTypes) GetDataTypes() []*DataType {
	if x != nil {
		return x.DataTypes
	}
	return nil
}

func (x *ModelDataTypes) GetModelId() int32 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

type AllModelsDataTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*ModelDataTypes      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllModelsDataTypes) Reset() {
	*x = AllModelsDataTypes{}
	mi := &file_cyber_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllModelsDataTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllModelsDataTypes) ProtoMessage() {}

func (x *AllModelsDataTypes) ProtoReflect() protoreflect.Message {
	mi := &file_cyber_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllModelsDataTypes.ProtoReflect.Descriptor instead.
func (*AllModelsDataTypes) Descriptor() ([]byte, []int) {
	return file_cyber_proto_rawDescGZIP(), []int{12}
}

func (x *AllModelsDataTypes) GetData() []*ModelDataTypes {
	if x != nil {
		return x.Data
	}
	return nil
}

type DataPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          int64                  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	ValueFloat    float32                `protobuf:"fixed32,2,opt,name=valueFloat,proto3" json:"valueFloat,omitempty"`
	ValueInt      int64                  `protobuf:"varint,3,opt,name=valueInt,proto3" json:"valueInt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPoint) Reset() {
	*x = DataPoint{}
	mi := &file_cyber_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPoint) ProtoMessage() {}

func (x *DataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_cyber_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPoint.ProtoReflect.Descriptor instead.
func (*DataPoint) Descriptor() ([]byte, []int) {
	return file_cyber_proto_rawDescGZIP(), []int{13}
}

func (x *DataPoint) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *DataPoint) GetValueFloat() float32 {
	if x != nil {
		return x.ValueFloat
	}
	return 0
}

func (x *DataPoint) GetValueInt() int64 {
	if x != nil {
		return x.ValueInt
	}
	return 0
}

type DataPoints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*DataPoint           `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPoints) Reset() {
	*x = DataPoints{}
	mi := &file_cyber_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPoints) ProtoMessage() {}

func (x *DataPoints) ProtoReflect() protoreflect.Message {
	mi := &file_cyber_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPoints.ProtoReflect.Descriptor instead.
func (*DataPoints) Descriptor() ([]byte, []int) {
	return file_cyber_proto_rawDescGZIP(), []int{14}
}

func (x *DataPoints) GetData() []*DataPoint {
	if x != nil {
		return x.Data
	}
	return nil
}

type Segment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     int64                  `protobuf:"varint,1,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime       int64                  `protobuf:"varint,2,opt,name=endTime,proto3" json:"endTime,omitempty"`
	DurationSec   int64                  `protobuf:"varint,3,opt,name=durationSec,proto3" json:"durationSec,omitempty"`
	Change        float32                `protobuf:"fixed32,4,opt,name=change,proto3" json:"change,omitempty"`
	StartValue    float32                `protobuf:"fixed32,5,opt,name=startValue,proto3" json:"startValue,omitempty"`
	EndValue      float32                `protobuf:"fixed32,6,opt,name=endValue,proto3" json:"endValue,omitempty"`
	Trend         string                 `protobuf:"bytes,7,opt,name=trend,proto3" json:"trend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Segment) Reset() {
	*x = Segment{}
	mi := &file_cyber_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment) ProtoMessage() {}

func (x *Segment) ProtoReflect() protoreflect.Message {
	mi := &file_cyber_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segment.ProtoReflect.Descriptor instead.
func (*Segment) Descriptor() ([]byte, []int) {
	return file_cyber_proto_rawDescGZIP(), []int{15}
}

func (x *Segment) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Segment) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *Segment) GetDurationSec() int64 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

func (x *Segment) GetChange() float32 {
	if x != nil {
		return x.Change
	}
	return 0
}

func (x *Segment) GetStartValue() float32 {
	if x != nil {
		return x.StartValue
	}
	return 0
}

func (x *Segment) GetEndValue() float32 {
	if x != nil {
		return x.EndValue
	}
	return 0
}

func (x *Segment) GetTrend() string {
	if x != nil {
		return x.Trend
	}
	return ""
}

type Segments struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Segments      []*Segment             `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Segments) Reset() {
	*x = Segments{}
	mi := &file_cyber_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Segments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segments) ProtoMessage() {}

func (x *Segments) ProtoReflect() protoreflect.Message {
	mi := &file_cyber_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segments.ProtoReflect.Descriptor instead.
func (*Segments) Descriptor() ([]byte, []int) {
	return file_cyber_proto_rawDescGZIP(), []int{16}
}

func (x *Segments) GetSegments() []*Segment {
	if x != nil {
		return x.Segments
	}
	return nil
}

var File_cyber_proto protoreflect.FileDescriptor

const file_cyber_proto_rawDesc = "" +
	"\n" +
	"\vcyber.proto\x12\tcybertele\"8\n" +
	"\vStatusReply\x12)\n" +
	"\x06status\x18\x01 \x01(\x0e2\x11.cybertele.StatusR\x06status\"\a\n" +
	"\x05Empty\"@\n" +
	"\x04Disk\x12\x10\n" +
	"\x03all\x18\x01 \x01(\x02R\x03all\x12\x12\n" +
	"\x04used\x18\x02 \x01(\x02R\x04used\x12\x12\n" +
	"\x04free\x18\x03 \x01(\x02R\x04free\"\xb5\x01\n" +
	"\vHealthReply\x12-\n" +
	"\bpostgres\x18\x01 \x01(\x0e2\x11.cybertele.StatusR\bpostgres\x12'\n" +
	"\x05mongo\x18\x02 \x01(\x0e2\x11.cybertele.StatusR\x05mongo\x12)\n" +
	"\x06parser\x18\x03 \x01(\x0e2\x11.cybertele.StatusR\x06parser\x12#\n" +
	"\x04disk\x18\x04 \x01(\v2\x0f.cybertele.DiskR\x04disk\"S\n" +
	"\fParserStatus\x12)\n" +
	"\x06parser\x18\x01 \x01(\x0e2\x11.cybertele.StatusR\x06parser\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"G\n" +
	"\vPageRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x0e\n" +
	"\x02sn\x18\x03 \x01(\tR\x02sn\"L\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\"\xe1\x01\n" +
	"\aMachine\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\tR\x02sn\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x12\n" +
	"\x04sync\x18\x03 \x01(\bR\x04sync\x12\"\n" +
	"\fgenerationId\x18\x04 \x01(\x05R\fgenerationId\x12\x18\n" +
	"\aclassId\x18\x05 \x01(\x05R\aclassId\x12\x1c\n" +
	"\tclassName\x18\x06 \x01(\tR\tclassName\x12&\n" +
	"\x0egenerationName\x18\a \x01(\tR\x0egenerationName\x12\x18\n" +
	"\amodelId\x18\b \x01(\x05R\amodelId\":\n" +
	"\bMachines\x12.\n" +
	"\bmachines\x18\x01 \x03(\v2\x12.cybertele.MachineR\bmachines\"~\n" +
	"\bDataType\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\ameaning\x18\x03 \x01(\tR\ameaning\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x12\x14\n" +
	"\x05group\x18\x05 \x01(\tR\x05group\"4\n" +
	"\tDataTypes\x12'\n" +
	"\x04data\x18\x01 \x03(\v2\x13.cybertele.DataTypeR\x04data\"s\n" +
	"\x0eModelDataTypes\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x121\n" +
	"\tdataTypes\x18\x02 \x03(\v2\x13.cybertele.DataTypeR\tdataTypes\x12\x18\n" +
	"\amodelId\x18\x03 \x01(\x05R\amodelId\"C\n" +
	"\x12AllModelsDataTypes\x12-\n" +
	"\x04data\x18\x01 \x03(\v2\x19.cybertele.ModelDataTypesR\x04data\"[\n" +
	"\tDataPoint\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x03R\x04time\x12\x1e\n" +
	"\n" +
	"valueFloat\x18\x02 \x01(\x02R\n" +
	"valueFloat\x12\x1a\n" +
	"\bvalueInt\x18\x03 \x01(\x03R\bvalueInt\"6\n" +
	"\n" +
	"DataPoints\x12(\n" +
	"\x04data\x18\x01 \x03(\v2\x14.cybertele.DataPointR\x04data\"\xcd\x01\n" +
	"\aSegment\x12\x1c\n" +
	"\tstartTime\x18\x01 \x01(\x03R\tstartTime\x12\x18\n" +
	"\aendTime\x18\x02 \x01(\x03R\aendTime\x12 \n" +
	"\vdurationSec\x18\x03 \x01(\x03R\vdurationSec\x12\x16\n" +
	"\x06change\x18\x04 \x01(\x02R\x06change\x12\x1e\n" +
	"\n" +
	"startValue\x18\x05 \x01(\x02R\n" +
	"startValue\x12\x1a\n" +
	"\bendValue\x18\x06 \x01(\x02R\bendValue\x12\x14\n" +
	"\x05trend\x18\a \x01(\tR\x05trend\":\n" +
	"\bSegments\x12.\n" +
	"\bsegments\x18\x01 \x03(\v2\x12.cybertele.SegmentR\bsegments*O\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\f\n" +
	"\bINACTIVE\x10\x02\x12\x06\n" +
	"\x02OK\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x04\x12\v\n" +
	"\aWARNING\x10\x05B\tZ\a./protob\x06proto3"

var (
	file_cyber_proto_rawDescOnce sync.Once
	file_cyber_proto_rawDescData []byte
)

func file_cyber_proto_rawDescGZIP() []byte {
	file_cyber_proto_rawDescOnce.Do(func() {
		file_cyber_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cyber_proto_rawDesc), len(file_cyber_proto_rawDesc)))
	})
	return file_cyber_proto_rawDescData
}

var file_cyber_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cyber_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_cyber_proto_goTypes = []any{
	(Status)(0),                // 0: cybertele.Status
	(*StatusReply)(nil),        // 1: cybertele.StatusReply
	(*Empty)(nil),              // 2: cybertele.Empty
	(*Disk)(nil),               // 3: cybertele.Disk
	(*HealthReply)(nil),        // 4: cybertele.HealthReply
	(*ParserStatus)(nil),       // 5: cybertele.ParserStatus
	(*PageRequest)(nil),        // 6: cybertele.PageRequest
	(*Pagination)(nil),         // 7: cybertele.Pagination
	(*Machine)(nil),            // 8: cybertele.Machine
	(*Machines)(nil),           // 9: cybertele.Machines
	(*DataType)(nil),           // 10: cybertele.DataType
	(*DataTypes)(nil),          // 11: cybertele.DataTypes
	(*ModelDataTypes)(nil),     // 12: cybertele.ModelDataTypes
	(*AllModelsDataTypes)(nil), // 13: cybertele.AllModelsDataTypes
	(*DataPoint)(nil),          // 14: cybertele.DataPoint
	(*DataPoints)(nil),         // 15: cybertele.DataPoints
	(*Segment)(nil),            // 16: cybertele.Segment
	(*Segments)(nil),           // 17: cybertele.Segments
}
var file_cyber_proto_depIdxs = []int32{
	0,  // 0: cybertele.StatusReply.status:type_name -> cybertele.Status
	0,  // 1: cybertele.HealthReply.postgres:type_name -> cybertele.Status
	0,  // 2: cybertele.HealthReply.mongo:type_name -> cybertele.Status
	0,  // 3: cybertele.HealthReply.parser:type_name -> cybertele.Status
	3,  // 4: cybertele.HealthReply.disk:type_name -> cybertele.Disk
	0,  // 5: cybertele.ParserStatus.parser:type_name -> cybertele.Status
	8,  // 6: cybertele.Machines.machines:type_name -> cybertele.Machine
	10, // 7: cybertele.DataTypes.data:type_name -> cybertele.DataType
	10, // 8: cybertele.ModelDataTypes.dataTypes:type_name -> cybertele.DataType
	12, // 9: cybertele.AllModelsDataTypes.data:type_name -> cybertele.ModelDataTypes
	14, // 10: cybertele.DataPoints.data:type_name -> cybertele.DataPoint
	16, // 11: cybertele.Segments.segments:type_name -> cybertele.Segment
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_cyber_proto_init() }
func file_cyber_proto_init() {
	if File_cyber_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cyber_proto_rawDesc), len(file_cyber_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cyber_proto_goTypes,
		DependencyIndexes: file_cyber_proto_depIdxs,
		EnumInfos:         file_cyber_proto_enumTypes,
		MessageInfos:      file_cyber_proto_msgTypes,
	}.Build()
	File_cyber_proto = out.File
	file_cyber_proto_goTypes = nil
	file_cyber_proto_depIdxs = nil
}
