// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: cybermetrica.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CybermetricaClient is the client API for Cybermetrica service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CybermetricaClient interface {
	// v1
	Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthReply, error)
	StartParser(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ParserStatus, error)
	StopParser(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ParserStatus, error)
	MachineStatisticPeriod(ctx context.Context, in *MachineStatisticRequest, opts ...grpc.CallOption) (*StatisticPeriod, error)
	// v2
	GetTelemetryParams(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TelemertyParams, error)
	CreateTelemetryParam(ctx context.Context, in *TelemertyParam, opts ...grpc.CallOption) (*StatusReply, error)
	UpdateTelemetryParam(ctx context.Context, in *TelemertyParam, opts ...grpc.CallOption) (*StatusReply, error)
	GetTimeline(ctx context.Context, in *TimelineRequest, opts ...grpc.CallOption) (*Timeline, error)
}

type cybermetricaClient struct {
	cc grpc.ClientConnInterface
}

func NewCybermetricaClient(cc grpc.ClientConnInterface) CybermetricaClient {
	return &cybermetricaClient{cc}
}

func (c *cybermetricaClient) Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthReply, error) {
	out := new(HealthReply)
	err := c.cc.Invoke(ctx, "/cybertele.Cybermetrica/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cybermetricaClient) StartParser(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ParserStatus, error) {
	out := new(ParserStatus)
	err := c.cc.Invoke(ctx, "/cybertele.Cybermetrica/StartParser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cybermetricaClient) StopParser(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ParserStatus, error) {
	out := new(ParserStatus)
	err := c.cc.Invoke(ctx, "/cybertele.Cybermetrica/StopParser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cybermetricaClient) MachineStatisticPeriod(ctx context.Context, in *MachineStatisticRequest, opts ...grpc.CallOption) (*StatisticPeriod, error) {
	out := new(StatisticPeriod)
	err := c.cc.Invoke(ctx, "/cybertele.Cybermetrica/MachineStatisticPeriod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cybermetricaClient) GetTelemetryParams(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TelemertyParams, error) {
	out := new(TelemertyParams)
	err := c.cc.Invoke(ctx, "/cybertele.Cybermetrica/GetTelemetryParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cybermetricaClient) CreateTelemetryParam(ctx context.Context, in *TelemertyParam, opts ...grpc.CallOption) (*StatusReply, error) {
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, "/cybertele.Cybermetrica/CreateTelemetryParam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cybermetricaClient) UpdateTelemetryParam(ctx context.Context, in *TelemertyParam, opts ...grpc.CallOption) (*StatusReply, error) {
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, "/cybertele.Cybermetrica/UpdateTelemetryParam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cybermetricaClient) GetTimeline(ctx context.Context, in *TimelineRequest, opts ...grpc.CallOption) (*Timeline, error) {
	out := new(Timeline)
	err := c.cc.Invoke(ctx, "/cybertele.Cybermetrica/GetTimeline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CybermetricaServer is the server API for Cybermetrica service.
// All implementations must embed UnimplementedCybermetricaServer
// for forward compatibility
type CybermetricaServer interface {
	// v1
	Health(context.Context, *Empty) (*HealthReply, error)
	StartParser(context.Context, *Empty) (*ParserStatus, error)
	StopParser(context.Context, *Empty) (*ParserStatus, error)
	MachineStatisticPeriod(context.Context, *MachineStatisticRequest) (*StatisticPeriod, error)
	// v2
	GetTelemetryParams(context.Context, *Empty) (*TelemertyParams, error)
	CreateTelemetryParam(context.Context, *TelemertyParam) (*StatusReply, error)
	UpdateTelemetryParam(context.Context, *TelemertyParam) (*StatusReply, error)
	GetTimeline(context.Context, *TimelineRequest) (*Timeline, error)
	mustEmbedUnimplementedCybermetricaServer()
}

// UnimplementedCybermetricaServer must be embedded to have forward compatible implementations.
type UnimplementedCybermetricaServer struct {
}

func (UnimplementedCybermetricaServer) Health(context.Context, *Empty) (*HealthReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedCybermetricaServer) StartParser(context.Context, *Empty) (*ParserStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartParser not implemented")
}
func (UnimplementedCybermetricaServer) StopParser(context.Context, *Empty) (*ParserStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopParser not implemented")
}
func (UnimplementedCybermetricaServer) MachineStatisticPeriod(context.Context, *MachineStatisticRequest) (*StatisticPeriod, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MachineStatisticPeriod not implemented")
}
func (UnimplementedCybermetricaServer) GetTelemetryParams(context.Context, *Empty) (*TelemertyParams, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTelemetryParams not implemented")
}
func (UnimplementedCybermetricaServer) CreateTelemetryParam(context.Context, *TelemertyParam) (*StatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTelemetryParam not implemented")
}
func (UnimplementedCybermetricaServer) UpdateTelemetryParam(context.Context, *TelemertyParam) (*StatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTelemetryParam not implemented")
}
func (UnimplementedCybermetricaServer) GetTimeline(context.Context, *TimelineRequest) (*Timeline, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTimeline not implemented")
}
func (UnimplementedCybermetricaServer) mustEmbedUnimplementedCybermetricaServer() {}

// UnsafeCybermetricaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CybermetricaServer will
// result in compilation errors.
type UnsafeCybermetricaServer interface {
	mustEmbedUnimplementedCybermetricaServer()
}

func RegisterCybermetricaServer(s grpc.ServiceRegistrar, srv CybermetricaServer) {
	s.RegisterService(&Cybermetrica_ServiceDesc, srv)
}

func _Cybermetrica_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybermetricaServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cybertele.Cybermetrica/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybermetricaServer).Health(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cybermetrica_StartParser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybermetricaServer).StartParser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cybertele.Cybermetrica/StartParser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybermetricaServer).StartParser(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cybermetrica_StopParser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybermetricaServer).StopParser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cybertele.Cybermetrica/StopParser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybermetricaServer).StopParser(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cybermetrica_MachineStatisticPeriod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MachineStatisticRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybermetricaServer).MachineStatisticPeriod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cybertele.Cybermetrica/MachineStatisticPeriod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybermetricaServer).MachineStatisticPeriod(ctx, req.(*MachineStatisticRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cybermetrica_GetTelemetryParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybermetricaServer).GetTelemetryParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cybertele.Cybermetrica/GetTelemetryParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybermetricaServer).GetTelemetryParams(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cybermetrica_CreateTelemetryParam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TelemertyParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybermetricaServer).CreateTelemetryParam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cybertele.Cybermetrica/CreateTelemetryParam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybermetricaServer).CreateTelemetryParam(ctx, req.(*TelemertyParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cybermetrica_UpdateTelemetryParam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TelemertyParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybermetricaServer).UpdateTelemetryParam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cybertele.Cybermetrica/UpdateTelemetryParam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybermetricaServer).UpdateTelemetryParam(ctx, req.(*TelemertyParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cybermetrica_GetTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybermetricaServer).GetTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cybertele.Cybermetrica/GetTimeline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybermetricaServer).GetTimeline(ctx, req.(*TimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Cybermetrica_ServiceDesc is the grpc.ServiceDesc for Cybermetrica service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cybermetrica_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cybertele.Cybermetrica",
	HandlerType: (*CybermetricaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _Cybermetrica_Health_Handler,
		},
		{
			MethodName: "StartParser",
			Handler:    _Cybermetrica_StartParser_Handler,
		},
		{
			MethodName: "StopParser",
			Handler:    _Cybermetrica_StopParser_Handler,
		},
		{
			MethodName: "MachineStatisticPeriod",
			Handler:    _Cybermetrica_MachineStatisticPeriod_Handler,
		},
		{
			MethodName: "GetTelemetryParams",
			Handler:    _Cybermetrica_GetTelemetryParams_Handler,
		},
		{
			MethodName: "CreateTelemetryParam",
			Handler:    _Cybermetrica_CreateTelemetryParam_Handler,
		},
		{
			MethodName: "UpdateTelemetryParam",
			Handler:    _Cybermetrica_UpdateTelemetryParam_Handler,
		},
		{
			MethodName: "GetTimeline",
			Handler:    _Cybermetrica_GetTimeline_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cybermetrica.proto",
}
