// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: cyberfuel.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CyberfuelClient is the client API for Cyberfuel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CyberfuelClient interface {
	Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthReply, error)
	CalcEvents(ctx context.Context, in *DataPoints, opts ...grpc.CallOption) (*Segments, error)
}

type cyberfuelClient struct {
	cc grpc.ClientConnInterface
}

func NewCyberfuelClient(cc grpc.ClientConnInterface) CyberfuelClient {
	return &cyberfuelClient{cc}
}

func (c *cyberfuelClient) Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthReply, error) {
	out := new(HealthReply)
	err := c.cc.Invoke(ctx, "/cybertele.Cyberfuel/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cyberfuelClient) CalcEvents(ctx context.Context, in *DataPoints, opts ...grpc.CallOption) (*Segments, error) {
	out := new(Segments)
	err := c.cc.Invoke(ctx, "/cybertele.Cyberfuel/CalcEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CyberfuelServer is the server API for Cyberfuel service.
// All implementations must embed UnimplementedCyberfuelServer
// for forward compatibility
type CyberfuelServer interface {
	Health(context.Context, *Empty) (*HealthReply, error)
	CalcEvents(context.Context, *DataPoints) (*Segments, error)
	mustEmbedUnimplementedCyberfuelServer()
}

// UnimplementedCyberfuelServer must be embedded to have forward compatible implementations.
type UnimplementedCyberfuelServer struct {
}

func (UnimplementedCyberfuelServer) Health(context.Context, *Empty) (*HealthReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedCyberfuelServer) CalcEvents(context.Context, *DataPoints) (*Segments, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalcEvents not implemented")
}
func (UnimplementedCyberfuelServer) mustEmbedUnimplementedCyberfuelServer() {}

// UnsafeCyberfuelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CyberfuelServer will
// result in compilation errors.
type UnsafeCyberfuelServer interface {
	mustEmbedUnimplementedCyberfuelServer()
}

func RegisterCyberfuelServer(s grpc.ServiceRegistrar, srv CyberfuelServer) {
	s.RegisterService(&Cyberfuel_ServiceDesc, srv)
}

func _Cyberfuel_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CyberfuelServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cybertele.Cyberfuel/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CyberfuelServer).Health(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cyberfuel_CalcEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataPoints)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CyberfuelServer).CalcEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cybertele.Cyberfuel/CalcEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CyberfuelServer).CalcEvents(ctx, req.(*DataPoints))
	}
	return interceptor(ctx, in, info, handler)
}

// Cyberfuel_ServiceDesc is the grpc.ServiceDesc for Cyberfuel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cyberfuel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cybertele.Cyberfuel",
	HandlerType: (*CyberfuelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _Cyberfuel_Health_Handler,
		},
		{
			MethodName: "CalcEvents",
			Handler:    _Cyberfuel_CalcEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cyberfuel.proto",
}
