syntax = "proto3";
import "cyber.proto";

package cybertele;

option go_package = "./proto";

service Cybermetrica {
    rpc Health (Empty) returns (HealthReply) {}
    rpc StartParser (Empty) returns (ParserStatus) {}
    rpc StopParser (Empty) returns (ParserStatus) {}
    rpc GetParserStatus (Empty) returns (ParserStatus) {}
    rpc GetParserLogs (PageRequest) returns (ParserMetricaLogsReply) {}
    rpc MachineLogs (PageRequest) returns (ParserMetricaLogsReply) {}
    rpc MachineStatisticPeriod (MachineStatisticRequest) returns (StatisticPeriod) {}
    rpc GetTelemetryParams (Empty) returns (TelemertyParams) {}
    rpc CreateTelemetryParam (TelemertyParam) returns (StatusReply) {}
    rpc UpdateTelemetryParam (TelemertyParam) returns (StatusReply) {}
    rpc GetTimeline (TimelineRequest) returns (Timeline) {}
    rpc AllMachinesWorkhours (Empty) returns (Workhours) {}
    rpc GetMachineWorkhourHistory(PageRequest) returns (WorkhourHistory) {}
}

message WorkhourItem {
    string date = 1;
    float value = 2;
}

message WorkhourHistory {
    repeated WorkhourItem data = 1;
    string sn = 2;
}

message MachineWorkhours {
    string machineNumber = 1;
    float motoHours = 2;
    string lastUpdateDate = 3;
    string imei = 4;
    string expDate = 5;
    bool active = 6;
}

message Workhours {
    repeated MachineWorkhours data = 1;
}

message ParserMetricaLog {
    int64 id = 1;
    string sn = 2;
    int32 count = 3;
    string startAt = 4;
    string endAt = 5;
    repeated string errors = 6;
    repeated string dataTypes = 7;
    string createdAt = 8;
}

message ParserMetricaLogsReply {
    repeated ParserMetricaLog data = 1;
    Pagination pagination = 2;
}

message MachineStatisticRequest {
    string sn = 1;
    int32 timezone = 2;
    string date = 3;
    string from = 4;
    string to = 5;
    string graph = 6;
    float code = 7;
    string period = 8;
}

message StatisticEngine {
    int64 all = 1;
    int64 idle = 2;
    int64 work = 3;
    int64 highRPM = 4;
}

message StatisticFuel {
    int32 consumption = 1;
    int32 drainVolume = 2;
    int32 drainCount = 3;
    int32 refillVolume = 4;
    int32 refillCount = 5;
}

message StatisticPeriodItem {
    string label = 1;
    float workhours = 2;
    StatisticEngine engine = 3;
    StatisticFuel fuel = 4;
    int64 job = 5;
    int64 connection = 6;
    int32 errorsCount = 7;
}

message StatisticPeriod {
    string sn = 1;
    int32 timezone = 2;
    string from = 3;
    string to = 4;
    string period = 5;
    string step = 6;
    repeated StatisticPeriodItem data = 7;
    float workhoursStart = 8;
    float workhoursEnd = 9;
    StatisticFuel fuel = 10;
    int32 errorsCount = 11;
    int64 connection = 12;
}

message TelemertyParams {
    repeated TelemertyParam params = 1;
}

message TelemertyParam {
    string code = 1;
    string label = 2;
    string units = 3;
    string description = 4;
}

message TimelineRequest {
    string sn = 1;
    string date = 2;
    int32 tz = 3;
}

message DataValuesRow {
    repeated float values = 1;
}

message ConnectionDataBlock {
    int64 id = 1;
    bool finished = 2;
    repeated DataValuesRow dataValues = 3;
}

message EventBlock {
    int64 start = 1;
    int64 end = 2;
    float value = 3;
    int64 id = 4;
}

message Timeline {
    string sn = 1;
    string date = 2;
    int32 tz = 3;
    int64 startTimeUnix = 4;
    repeated string params = 5;
    repeated EventBlock connections = 6;
    repeated EventBlock engines = 7;
    repeated EventBlock jobs = 8;
    repeated EventBlock errors = 9;
    repeated ConnectionDataBlock data = 10;
}