// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: events.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventsCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        int32                  `protobuf:"varint,1,opt,name=events,proto3" json:"events,omitempty"`
	Errors        int32                  `protobuf:"varint,2,opt,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsCount) Reset() {
	*x = EventsCount{}
	mi := &file_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsCount) ProtoMessage() {}

func (x *EventsCount) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsCount.ProtoReflect.Descriptor instead.
func (*EventsCount) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

func (x *EventsCount) GetEvents() int32 {
	if x != nil {
		return x.Events
	}
	return 0
}

func (x *EventsCount) GetErrors() int32 {
	if x != nil {
		return x.Errors
	}
	return 0
}

type SetEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            string                 `protobuf:"bytes,1,opt,name=sn,proto3" json:"sn,omitempty"`
	Events        []*Event               `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetEventsRequest) Reset() {
	*x = SetEventsRequest{}
	mi := &file_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEventsRequest) ProtoMessage() {}

func (x *SetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEventsRequest.ProtoReflect.Descriptor instead.
func (*SetEventsRequest) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

func (x *SetEventsRequest) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *SetEventsRequest) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type GetMachineEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            string                 `protobuf:"bytes,1,opt,name=sn,proto3" json:"sn,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Tz            int32                  `protobuf:"varint,3,opt,name=tz,proto3" json:"tz,omitempty"`
	ConnectionId  int64                  `protobuf:"varint,4,opt,name=connectionId,proto3" json:"connectionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMachineEventsRequest) Reset() {
	*x = GetMachineEventsRequest{}
	mi := &file_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMachineEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMachineEventsRequest) ProtoMessage() {}

func (x *GetMachineEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMachineEventsRequest.ProtoReflect.Descriptor instead.
func (*GetMachineEventsRequest) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{2}
}

func (x *GetMachineEventsRequest) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *GetMachineEventsRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetMachineEventsRequest) GetTz() int32 {
	if x != nil {
		return x.Tz
	}
	return 0
}

func (x *GetMachineEventsRequest) GetConnectionId() int64 {
	if x != nil {
		return x.ConnectionId
	}
	return 0
}

type GetGroupEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            []string               `protobuf:"bytes,1,rep,name=sn,proto3" json:"sn,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Tz            int32                  `protobuf:"varint,3,opt,name=tz,proto3" json:"tz,omitempty"`
	FromId        int64                  `protobuf:"varint,4,opt,name=fromId,proto3" json:"fromId,omitempty"`
	Direction     string                 `protobuf:"bytes,5,opt,name=direction,proto3" json:"direction,omitempty"`
	Limit         int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupEventsRequest) Reset() {
	*x = GetGroupEventsRequest{}
	mi := &file_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupEventsRequest) ProtoMessage() {}

func (x *GetGroupEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupEventsRequest.ProtoReflect.Descriptor instead.
func (*GetGroupEventsRequest) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{3}
}

func (x *GetGroupEventsRequest) GetSn() []string {
	if x != nil {
		return x.Sn
	}
	return nil
}

func (x *GetGroupEventsRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetGroupEventsRequest) GetTz() int32 {
	if x != nil {
		return x.Tz
	}
	return 0
}

func (x *GetGroupEventsRequest) GetFromId() int64 {
	if x != nil {
		return x.FromId
	}
	return 0
}

func (x *GetGroupEventsRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *GetGroupEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type EventsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsReply) Reset() {
	*x = EventsReply{}
	mi := &file_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsReply) ProtoMessage() {}

func (x *EventsReply) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsReply.ProtoReflect.Descriptor instead.
func (*EventsReply) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{4}
}

func (x *EventsReply) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_events_proto protoreflect.FileDescriptor

const file_events_proto_rawDesc = "" +
	"\n" +
	"\fevents.proto\x12\tcybertele\x1a\vcyber.proto\"=\n" +
	"\vEventsCount\x12\x16\n" +
	"\x06events\x18\x01 \x01(\x05R\x06events\x12\x16\n" +
	"\x06errors\x18\x02 \x01(\x05R\x06errors\"L\n" +
	"\x10SetEventsRequest\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\tR\x02sn\x12(\n" +
	"\x06events\x18\x02 \x03(\v2\x10.cybertele.EventR\x06events\"q\n" +
	"\x17GetMachineEventsRequest\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\tR\x02sn\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x0e\n" +
	"\x02tz\x18\x03 \x01(\x05R\x02tz\x12\"\n" +
	"\fconnectionId\x18\x04 \x01(\x03R\fconnectionId\"\x97\x01\n" +
	"\x15GetGroupEventsRequest\x12\x0e\n" +
	"\x02sn\x18\x01 \x03(\tR\x02sn\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x0e\n" +
	"\x02tz\x18\x03 \x01(\x05R\x02tz\x12\x16\n" +
	"\x06fromId\x18\x04 \x01(\x03R\x06fromId\x12\x1c\n" +
	"\tdirection\x18\x05 \x01(\tR\tdirection\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\"7\n" +
	"\vEventsReply\x12(\n" +
	"\x06events\x18\x01 \x03(\v2\x10.cybertele.EventR\x06events2\xfa\x02\n" +
	"\vCyberevents\x124\n" +
	"\x06Health\x12\x10.cybertele.Empty\x1a\x16.cybertele.HealthReply\"\x00\x12B\n" +
	"\tSetEvents\x12\x1b.cybertele.SetEventsRequest\x1a\x16.cybertele.StatusReply\"\x00\x12P\n" +
	"\x10GetMachineEvents\x12\".cybertele.GetMachineEventsRequest\x1a\x16.cybertele.EventsReply\"\x00\x12L\n" +
	"\x0eGetGroupEvents\x12 .cybertele.GetGroupEventsRequest\x1a\x16.cybertele.EventsReply\"\x00\x12Q\n" +
	"\x13GetGroupEventsCount\x12 .cybertele.GetGroupEventsRequest\x1a\x16.cybertele.EventsCount\"\x00B\tZ\a./protob\x06proto3"

var (
	file_events_proto_rawDescOnce sync.Once
	file_events_proto_rawDescData []byte
)

func file_events_proto_rawDescGZIP() []byte {
	file_events_proto_rawDescOnce.Do(func() {
		file_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)))
	})
	return file_events_proto_rawDescData
}

var file_events_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_events_proto_goTypes = []any{
	(*EventsCount)(nil),             // 0: cybertele.EventsCount
	(*SetEventsRequest)(nil),        // 1: cybertele.SetEventsRequest
	(*GetMachineEventsRequest)(nil), // 2: cybertele.GetMachineEventsRequest
	(*GetGroupEventsRequest)(nil),   // 3: cybertele.GetGroupEventsRequest
	(*EventsReply)(nil),             // 4: cybertele.EventsReply
	(*Event)(nil),                   // 5: cybertele.Event
	(*Empty)(nil),                   // 6: cybertele.Empty
	(*HealthReply)(nil),             // 7: cybertele.HealthReply
	(*StatusReply)(nil),             // 8: cybertele.StatusReply
}
var file_events_proto_depIdxs = []int32{
	5, // 0: cybertele.SetEventsRequest.events:type_name -> cybertele.Event
	5, // 1: cybertele.EventsReply.events:type_name -> cybertele.Event
	6, // 2: cybertele.Cyberevents.Health:input_type -> cybertele.Empty
	1, // 3: cybertele.Cyberevents.SetEvents:input_type -> cybertele.SetEventsRequest
	2, // 4: cybertele.Cyberevents.GetMachineEvents:input_type -> cybertele.GetMachineEventsRequest
	3, // 5: cybertele.Cyberevents.GetGroupEvents:input_type -> cybertele.GetGroupEventsRequest
	3, // 6: cybertele.Cyberevents.GetGroupEventsCount:input_type -> cybertele.GetGroupEventsRequest
	7, // 7: cybertele.Cyberevents.Health:output_type -> cybertele.HealthReply
	8, // 8: cybertele.Cyberevents.SetEvents:output_type -> cybertele.StatusReply
	4, // 9: cybertele.Cyberevents.GetMachineEvents:output_type -> cybertele.EventsReply
	4, // 10: cybertele.Cyberevents.GetGroupEvents:output_type -> cybertele.EventsReply
	0, // 11: cybertele.Cyberevents.GetGroupEventsCount:output_type -> cybertele.EventsCount
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_events_proto_init() }
func file_events_proto_init() {
	if File_events_proto != nil {
		return
	}
	file_cyber_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_events_proto_goTypes,
		DependencyIndexes: file_events_proto_depIdxs,
		MessageInfos:      file_events_proto_msgTypes,
	}.Build()
	File_events_proto = out.File
	file_events_proto_goTypes = nil
	file_events_proto_depIdxs = nil
}
