// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.12.4
// source: events.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Cyberevents_Health_FullMethodName         = "/cybertele.Cyberevents/Health"
	Cyberevents_SetEvents_FullMethodName      = "/cybertele.Cyberevents/SetEvents"
	Cyberevents_GetEvents_FullMethodName      = "/cybertele.Cyberevents/GetEvents"
	Cyberevents_GetGroupEvents_FullMethodName = "/cybertele.Cyberevents/GetGroupEvents"
)

// CybereventsClient is the client API for Cyberevents service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CybereventsClient interface {
	Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthReply, error)
	SetEvents(ctx context.Context, in *SetEventsRequest, opts ...grpc.CallOption) (*StatusReply, error)
	GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*EventsReply, error)
	GetGroupEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*EventsReply, error)
}

type cybereventsClient struct {
	cc grpc.ClientConnInterface
}

func NewCybereventsClient(cc grpc.ClientConnInterface) CybereventsClient {
	return &cybereventsClient{cc}
}

func (c *cybereventsClient) Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthReply)
	err := c.cc.Invoke(ctx, Cyberevents_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cybereventsClient) SetEvents(ctx context.Context, in *SetEventsRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, Cyberevents_SetEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cybereventsClient) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*EventsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventsReply)
	err := c.cc.Invoke(ctx, Cyberevents_GetEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cybereventsClient) GetGroupEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*EventsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventsReply)
	err := c.cc.Invoke(ctx, Cyberevents_GetGroupEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CybereventsServer is the server API for Cyberevents service.
// All implementations must embed UnimplementedCybereventsServer
// for forward compatibility.
type CybereventsServer interface {
	Health(context.Context, *Empty) (*HealthReply, error)
	SetEvents(context.Context, *SetEventsRequest) (*StatusReply, error)
	GetEvents(context.Context, *GetEventsRequest) (*EventsReply, error)
	GetGroupEvents(context.Context, *GetEventsRequest) (*EventsReply, error)
	mustEmbedUnimplementedCybereventsServer()
}

// UnimplementedCybereventsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCybereventsServer struct{}

func (UnimplementedCybereventsServer) Health(context.Context, *Empty) (*HealthReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedCybereventsServer) SetEvents(context.Context, *SetEventsRequest) (*StatusReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SetEvents not implemented")
}
func (UnimplementedCybereventsServer) GetEvents(context.Context, *GetEventsRequest) (*EventsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEvents not implemented")
}
func (UnimplementedCybereventsServer) GetGroupEvents(context.Context, *GetEventsRequest) (*EventsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupEvents not implemented")
}
func (UnimplementedCybereventsServer) mustEmbedUnimplementedCybereventsServer() {}
func (UnimplementedCybereventsServer) testEmbeddedByValue()                     {}

// UnsafeCybereventsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CybereventsServer will
// result in compilation errors.
type UnsafeCybereventsServer interface {
	mustEmbedUnimplementedCybereventsServer()
}

func RegisterCybereventsServer(s grpc.ServiceRegistrar, srv CybereventsServer) {
	// If the following call panics, it indicates UnimplementedCybereventsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Cyberevents_ServiceDesc, srv)
}

func _Cyberevents_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybereventsServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cyberevents_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybereventsServer).Health(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cyberevents_SetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybereventsServer).SetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cyberevents_SetEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybereventsServer).SetEvents(ctx, req.(*SetEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cyberevents_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybereventsServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cyberevents_GetEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybereventsServer).GetEvents(ctx, req.(*GetEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cyberevents_GetGroupEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybereventsServer).GetGroupEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cyberevents_GetGroupEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybereventsServer).GetGroupEvents(ctx, req.(*GetEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Cyberevents_ServiceDesc is the grpc.ServiceDesc for Cyberevents service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cyberevents_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cybertele.Cyberevents",
	HandlerType: (*CybereventsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _Cyberevents_Health_Handler,
		},
		{
			MethodName: "SetEvents",
			Handler:    _Cyberevents_SetEvents_Handler,
		},
		{
			MethodName: "GetEvents",
			Handler:    _Cyberevents_GetEvents_Handler,
		},
		{
			MethodName: "GetGroupEvents",
			Handler:    _Cyberevents_GetGroupEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "events.proto",
}
