syntax = "proto3";
import "cyber.proto";

package cybertele;

option go_package = "./proto";

service Cyberevents {
    rpc Health (Empty) returns (HealthReply) {}
    rpc SetEvents (SetEventsRequest) returns (StatusReply) {}
    rpc GetMachineEvents (GetMachineEventsRequest) returns (EventsReply) {}
    rpc GetGroupEvents (GetGroupEventsRequest) returns (EventsReply) {}
}

message SetEventsRequest {
    string sn = 1;
    repeated EventMessage events = 2;
}

message GetMachineEventsRequest {
    string sn = 1;
    string date = 2;
    int32 tz = 3;
    int64 connectionId = 4;
}

message GetGroupEventsRequest {
    repeated string sn = 1;
    string date = 2;
    int32 tz = 3;
}

message EventsReply {
    repeated EventMessage events = 1;
}

message EventMessage {
    int64 id = 1;
    string startTime = 2;
    string endTime = 3;
    string type = 4;
    string level = 5;
    string message = 6;
    string description = 7;
    float errorCode = 8;
    bool isValid = 9;
    string system = 10;
    int64 startTimeUnix = 11;
    int64 endTimeUnix = 12;
    string sn = 13;
    int64 connectionId = 14;
}