// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: events.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetEventsRequest) Reset() {
	*x = SetEventsRequest{}
	mi := &file_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEventsRequest) ProtoMessage() {}

func (x *SetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEventsRequest.ProtoReflect.Descriptor instead.
func (*SetEventsRequest) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

type GetEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsRequest) Reset() {
	*x = GetEventsRequest{}
	mi := &file_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsRequest) ProtoMessage() {}

func (x *GetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsRequest.ProtoReflect.Descriptor instead.
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

type EventsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*EventMessage        `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsReply) Reset() {
	*x = EventsReply{}
	mi := &file_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsReply) ProtoMessage() {}

func (x *EventsReply) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsReply.ProtoReflect.Descriptor instead.
func (*EventsReply) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{2}
}

func (x *EventsReply) GetEvents() []*EventMessage {
	if x != nil {
		return x.Events
	}
	return nil
}

type EventMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StartTime     string                 `protobuf:"bytes,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime       string                 `protobuf:"bytes,3,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Level         string                 `protobuf:"bytes,5,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	ErrorCode     float32                `protobuf:"fixed32,8,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	IsValid       bool                   `protobuf:"varint,9,opt,name=isValid,proto3" json:"isValid,omitempty"`
	System        string                 `protobuf:"bytes,10,opt,name=system,proto3" json:"system,omitempty"`
	StartTimeUnix int64                  `protobuf:"varint,11,opt,name=startTimeUnix,proto3" json:"startTimeUnix,omitempty"`
	EndTimeUnix   int64                  `protobuf:"varint,12,opt,name=endTimeUnix,proto3" json:"endTimeUnix,omitempty"`
	Sn            string                 `protobuf:"bytes,13,opt,name=sn,proto3" json:"sn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventMessage) Reset() {
	*x = EventMessage{}
	mi := &file_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMessage) ProtoMessage() {}

func (x *EventMessage) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMessage.ProtoReflect.Descriptor instead.
func (*EventMessage) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{3}
}

func (x *EventMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EventMessage) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *EventMessage) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *EventMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventMessage) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *EventMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EventMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EventMessage) GetErrorCode() float32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *EventMessage) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *EventMessage) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *EventMessage) GetStartTimeUnix() int64 {
	if x != nil {
		return x.StartTimeUnix
	}
	return 0
}

func (x *EventMessage) GetEndTimeUnix() int64 {
	if x != nil {
		return x.EndTimeUnix
	}
	return 0
}

func (x *EventMessage) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

var File_events_proto protoreflect.FileDescriptor

const file_events_proto_rawDesc = "" +
	"\n" +
	"\fevents.proto\x12\tcybertele\x1a\vcyber.proto\"\x12\n" +
	"\x10SetEventsRequest\"\x12\n" +
	"\x10GetEventsRequest\">\n" +
	"\vEventsReply\x12/\n" +
	"\x06events\x18\x01 \x03(\v2\x17.cybertele.EventMessageR\x06events\"\xe4\x02\n" +
	"\fEventMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\tstartTime\x18\x02 \x01(\tR\tstartTime\x12\x18\n" +
	"\aendTime\x18\x03 \x01(\tR\aendTime\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x14\n" +
	"\x05level\x18\x05 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1c\n" +
	"\terrorCode\x18\b \x01(\x02R\terrorCode\x12\x18\n" +
	"\aisValid\x18\t \x01(\bR\aisValid\x12\x16\n" +
	"\x06system\x18\n" +
	" \x01(\tR\x06system\x12$\n" +
	"\rstartTimeUnix\x18\v \x01(\x03R\rstartTimeUnix\x12 \n" +
	"\vendTimeUnix\x18\f \x01(\x03R\vendTimeUnix\x12\x0e\n" +
	"\x02sn\x18\r \x01(\tR\x02sn2\x94\x02\n" +
	"\vCyberevents\x124\n" +
	"\x06Health\x12\x10.cybertele.Empty\x1a\x16.cybertele.HealthReply\"\x00\x12B\n" +
	"\tSetEvents\x12\x1b.cybertele.SetEventsRequest\x1a\x16.cybertele.StatusReply\"\x00\x12B\n" +
	"\tGetEvents\x12\x1b.cybertele.GetEventsRequest\x1a\x16.cybertele.EventsReply\"\x00\x12G\n" +
	"\x0eGetGroupEvents\x12\x1b.cybertele.GetEventsRequest\x1a\x16.cybertele.EventsReply\"\x00B\tZ\a./protob\x06proto3"

var (
	file_events_proto_rawDescOnce sync.Once
	file_events_proto_rawDescData []byte
)

func file_events_proto_rawDescGZIP() []byte {
	file_events_proto_rawDescOnce.Do(func() {
		file_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)))
	})
	return file_events_proto_rawDescData
}

var file_events_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_events_proto_goTypes = []any{
	(*SetEventsRequest)(nil), // 0: cybertele.SetEventsRequest
	(*GetEventsRequest)(nil), // 1: cybertele.GetEventsRequest
	(*EventsReply)(nil),      // 2: cybertele.EventsReply
	(*EventMessage)(nil),     // 3: cybertele.EventMessage
	(*Empty)(nil),            // 4: cybertele.Empty
	(*HealthReply)(nil),      // 5: cybertele.HealthReply
	(*StatusReply)(nil),      // 6: cybertele.StatusReply
}
var file_events_proto_depIdxs = []int32{
	3, // 0: cybertele.EventsReply.events:type_name -> cybertele.EventMessage
	4, // 1: cybertele.Cyberevents.Health:input_type -> cybertele.Empty
	0, // 2: cybertele.Cyberevents.SetEvents:input_type -> cybertele.SetEventsRequest
	1, // 3: cybertele.Cyberevents.GetEvents:input_type -> cybertele.GetEventsRequest
	1, // 4: cybertele.Cyberevents.GetGroupEvents:input_type -> cybertele.GetEventsRequest
	5, // 5: cybertele.Cyberevents.Health:output_type -> cybertele.HealthReply
	6, // 6: cybertele.Cyberevents.SetEvents:output_type -> cybertele.StatusReply
	2, // 7: cybertele.Cyberevents.GetEvents:output_type -> cybertele.EventsReply
	2, // 8: cybertele.Cyberevents.GetGroupEvents:output_type -> cybertele.EventsReply
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_events_proto_init() }
func file_events_proto_init() {
	if File_events_proto != nil {
		return
	}
	file_cyber_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_events_proto_goTypes,
		DependencyIndexes: file_events_proto_depIdxs,
		MessageInfos:      file_events_proto_msgTypes,
	}.Build()
	File_events_proto = out.File
	file_events_proto_goTypes = nil
	file_events_proto_depIdxs = nil
}
