syntax = "proto3";
import "cyber.proto";

package cybertele;

option go_package = "./proto";

service Cyberevents {
    rpc Health (Empty) returns (HealthReply) {}
    rpc SetEvents (SetEventsRequest) returns (StatusReply) {}
    rpc GetMachineEvents (GetMachineEventsRequest) returns (EventsReply) {}
    rpc GetGroupEvents (GetGroupEventsRequest) returns (EventsReply) {}
    rpc GetGroupEventsCount (GetGroupEventsRequest) returns (EventsCount) {}
}

message EventsCount {
    int32 events = 1;
    int32 errors = 2;
}

message SetEventsRequest {
    string sn = 1;
    repeated Event events = 2;
}

message GetMachineEventsRequest {
    string sn = 1;
    string date = 2;
    int32 tz = 3;
    int64 connectionId = 4;
}

message GetGroupEventsRequest {
    repeated string sn = 1;
    string date = 2;
    int32 tz = 3;
    int64 fromId = 4;
    string direction = 5;
    int32 limit = 6;
}

message EventsReply {
    repeated Event events = 1;
}