// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: maintenance.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_maintenance_proto protoreflect.FileDescriptor

const file_maintenance_proto_rawDesc = "" +
	"\n" +
	"\x11maintenance.proto\x12\tcybertele\x1a\vcyber.proto2K\n" +
	"\x13MaintenanceForecast\x124\n" +
	"\x06Health\x12\x10.cybertele.Empty\x1a\x16.cybertele.HealthReply\"\x00B\tZ\a./protob\x06proto3"

var file_maintenance_proto_goTypes = []any{
	(*Empty)(nil),       // 0: cybertele.Empty
	(*HealthReply)(nil), // 1: cybertele.HealthReply
}
var file_maintenance_proto_depIdxs = []int32{
	0, // 0: cybertele.MaintenanceForecast.Health:input_type -> cybertele.Empty
	1, // 1: cybertele.MaintenanceForecast.Health:output_type -> cybertele.HealthReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_maintenance_proto_init() }
func file_maintenance_proto_init() {
	if File_maintenance_proto != nil {
		return
	}
	file_cyber_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_maintenance_proto_rawDesc), len(file_maintenance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_maintenance_proto_goTypes,
		DependencyIndexes: file_maintenance_proto_depIdxs,
	}.Build()
	File_maintenance_proto = out.File
	file_maintenance_proto_goTypes = nil
	file_maintenance_proto_depIdxs = nil
}
