// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.12.4
// source: maintenance.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MaintenanceForecast_Health_FullMethodName             = "/cybertele.MaintenanceForecast/Health"
	MaintenanceForecast_GetForecast_FullMethodName        = "/cybertele.MaintenanceForecast/GetForecast"
	MaintenanceForecast_BuildForecast_FullMethodName      = "/cybertele.MaintenanceForecast/BuildForecast"
	MaintenanceForecast_GetMahineForecasts_FullMethodName = "/cybertele.MaintenanceForecast/GetMahineForecasts"
)

// MaintenanceForecastClient is the client API for MaintenanceForecast service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MaintenanceForecastClient interface {
	Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthReply, error)
	GetForecast(ctx context.Context, in *ForecastRequest, opts ...grpc.CallOption) (*ForecastReply, error)
	BuildForecast(ctx context.Context, in *ForecastRequest, opts ...grpc.CallOption) (*ForecastReply, error)
	GetMahineForecasts(ctx context.Context, in *ForecastRequest, opts ...grpc.CallOption) (*ForecastsReply, error)
}

type maintenanceForecastClient struct {
	cc grpc.ClientConnInterface
}

func NewMaintenanceForecastClient(cc grpc.ClientConnInterface) MaintenanceForecastClient {
	return &maintenanceForecastClient{cc}
}

func (c *maintenanceForecastClient) Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthReply)
	err := c.cc.Invoke(ctx, MaintenanceForecast_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintenanceForecastClient) GetForecast(ctx context.Context, in *ForecastRequest, opts ...grpc.CallOption) (*ForecastReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForecastReply)
	err := c.cc.Invoke(ctx, MaintenanceForecast_GetForecast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintenanceForecastClient) BuildForecast(ctx context.Context, in *ForecastRequest, opts ...grpc.CallOption) (*ForecastReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForecastReply)
	err := c.cc.Invoke(ctx, MaintenanceForecast_BuildForecast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintenanceForecastClient) GetMahineForecasts(ctx context.Context, in *ForecastRequest, opts ...grpc.CallOption) (*ForecastsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForecastsReply)
	err := c.cc.Invoke(ctx, MaintenanceForecast_GetMahineForecasts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MaintenanceForecastServer is the server API for MaintenanceForecast service.
// All implementations must embed UnimplementedMaintenanceForecastServer
// for forward compatibility.
type MaintenanceForecastServer interface {
	Health(context.Context, *Empty) (*HealthReply, error)
	GetForecast(context.Context, *ForecastRequest) (*ForecastReply, error)
	BuildForecast(context.Context, *ForecastRequest) (*ForecastReply, error)
	GetMahineForecasts(context.Context, *ForecastRequest) (*ForecastsReply, error)
	mustEmbedUnimplementedMaintenanceForecastServer()
}

// UnimplementedMaintenanceForecastServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMaintenanceForecastServer struct{}

func (UnimplementedMaintenanceForecastServer) Health(context.Context, *Empty) (*HealthReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedMaintenanceForecastServer) GetForecast(context.Context, *ForecastRequest) (*ForecastReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetForecast not implemented")
}
func (UnimplementedMaintenanceForecastServer) BuildForecast(context.Context, *ForecastRequest) (*ForecastReply, error) {
	return nil, status.Error(codes.Unimplemented, "method BuildForecast not implemented")
}
func (UnimplementedMaintenanceForecastServer) GetMahineForecasts(context.Context, *ForecastRequest) (*ForecastsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMahineForecasts not implemented")
}
func (UnimplementedMaintenanceForecastServer) mustEmbedUnimplementedMaintenanceForecastServer() {}
func (UnimplementedMaintenanceForecastServer) testEmbeddedByValue()                             {}

// UnsafeMaintenanceForecastServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MaintenanceForecastServer will
// result in compilation errors.
type UnsafeMaintenanceForecastServer interface {
	mustEmbedUnimplementedMaintenanceForecastServer()
}

func RegisterMaintenanceForecastServer(s grpc.ServiceRegistrar, srv MaintenanceForecastServer) {
	// If the following call panics, it indicates UnimplementedMaintenanceForecastServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MaintenanceForecast_ServiceDesc, srv)
}

func _MaintenanceForecast_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintenanceForecastServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintenanceForecast_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintenanceForecastServer).Health(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintenanceForecast_GetForecast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForecastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintenanceForecastServer).GetForecast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintenanceForecast_GetForecast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintenanceForecastServer).GetForecast(ctx, req.(*ForecastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintenanceForecast_BuildForecast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForecastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintenanceForecastServer).BuildForecast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintenanceForecast_BuildForecast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintenanceForecastServer).BuildForecast(ctx, req.(*ForecastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MaintenanceForecast_GetMahineForecasts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForecastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintenanceForecastServer).GetMahineForecasts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MaintenanceForecast_GetMahineForecasts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintenanceForecastServer).GetMahineForecasts(ctx, req.(*ForecastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MaintenanceForecast_ServiceDesc is the grpc.ServiceDesc for MaintenanceForecast service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MaintenanceForecast_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cybertele.MaintenanceForecast",
	HandlerType: (*MaintenanceForecastServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _MaintenanceForecast_Health_Handler,
		},
		{
			MethodName: "GetForecast",
			Handler:    _MaintenanceForecast_GetForecast_Handler,
		},
		{
			MethodName: "BuildForecast",
			Handler:    _MaintenanceForecast_BuildForecast_Handler,
		},
		{
			MethodName: "GetMahineForecasts",
			Handler:    _MaintenanceForecast_GetMahineForecasts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "maintenance.proto",
}
