// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: mongo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MongoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            string                 `protobuf:"bytes,1,opt,name=sn,proto3" json:"sn,omitempty"`
	MachineType   string                 `protobuf:"bytes,2,opt,name=machineType,proto3" json:"machineType,omitempty"`
	ErrorCode     []float32              `protobuf:"fixed32,3,rep,packed,name=errorCode,proto3" json:"errorCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MongoRequest) Reset() {
	*x = MongoRequest{}
	mi := &file_mongo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MongoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MongoRequest) ProtoMessage() {}

func (x *MongoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mongo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MongoRequest.ProtoReflect.Descriptor instead.
func (*MongoRequest) Descriptor() ([]byte, []int) {
	return file_mongo_proto_rawDescGZIP(), []int{0}
}

func (x *MongoRequest) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *MongoRequest) GetMachineType() string {
	if x != nil {
		return x.MachineType
	}
	return ""
}

func (x *MongoRequest) GetErrorCode() []float32 {
	if x != nil {
		return x.ErrorCode
	}
	return nil
}

type MongoMachineType struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type            string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	LocarusProtocol int32                  `protobuf:"varint,3,opt,name=locarusProtocol,proto3" json:"locarusProtocol,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MongoMachineType) Reset() {
	*x = MongoMachineType{}
	mi := &file_mongo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MongoMachineType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MongoMachineType) ProtoMessage() {}

func (x *MongoMachineType) ProtoReflect() protoreflect.Message {
	mi := &file_mongo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MongoMachineType.ProtoReflect.Descriptor instead.
func (*MongoMachineType) Descriptor() ([]byte, []int) {
	return file_mongo_proto_rawDescGZIP(), []int{1}
}

func (x *MongoMachineType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MongoMachineType) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MongoMachineType) GetLocarusProtocol() int32 {
	if x != nil {
		return x.LocarusProtocol
	}
	return 0
}

type MongoMachineTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*MongoMachineType    `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MongoMachineTypes) Reset() {
	*x = MongoMachineTypes{}
	mi := &file_mongo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MongoMachineTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MongoMachineTypes) ProtoMessage() {}

func (x *MongoMachineTypes) ProtoReflect() protoreflect.Message {
	mi := &file_mongo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MongoMachineTypes.ProtoReflect.Descriptor instead.
func (*MongoMachineTypes) Descriptor() ([]byte, []int) {
	return file_mongo_proto_rawDescGZIP(), []int{2}
}

func (x *MongoMachineTypes) GetData() []*MongoMachineType {
	if x != nil {
		return x.Data
	}
	return nil
}

type MongoMachine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            string                 `protobuf:"bytes,1,opt,name=sn,proto3" json:"sn,omitempty"`
	MachineType   string                 `protobuf:"bytes,2,opt,name=machineType,proto3" json:"machineType,omitempty"`
	Imei          string                 `protobuf:"bytes,3,opt,name=imei,proto3" json:"imei,omitempty"`
	Status        bool                   `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	ExpDate       string                 `protobuf:"bytes,5,opt,name=expDate,proto3" json:"expDate,omitempty"`
	Trackable     bool                   `protobuf:"varint,6,opt,name=trackable,proto3" json:"trackable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MongoMachine) Reset() {
	*x = MongoMachine{}
	mi := &file_mongo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MongoMachine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MongoMachine) ProtoMessage() {}

func (x *MongoMachine) ProtoReflect() protoreflect.Message {
	mi := &file_mongo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MongoMachine.ProtoReflect.Descriptor instead.
func (*MongoMachine) Descriptor() ([]byte, []int) {
	return file_mongo_proto_rawDescGZIP(), []int{3}
}

func (x *MongoMachine) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *MongoMachine) GetMachineType() string {
	if x != nil {
		return x.MachineType
	}
	return ""
}

func (x *MongoMachine) GetImei() string {
	if x != nil {
		return x.Imei
	}
	return ""
}

func (x *MongoMachine) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *MongoMachine) GetExpDate() string {
	if x != nil {
		return x.ExpDate
	}
	return ""
}

func (x *MongoMachine) GetTrackable() bool {
	if x != nil {
		return x.Trackable
	}
	return false
}

type MongoMachines struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*MongoMachine        `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MongoMachines) Reset() {
	*x = MongoMachines{}
	mi := &file_mongo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MongoMachines) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MongoMachines) ProtoMessage() {}

func (x *MongoMachines) ProtoReflect() protoreflect.Message {
	mi := &file_mongo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MongoMachines.ProtoReflect.Descriptor instead.
func (*MongoMachines) Descriptor() ([]byte, []int) {
	return file_mongo_proto_rawDescGZIP(), []int{4}
}

func (x *MongoMachines) GetData() []*MongoMachine {
	if x != nil {
		return x.Data
	}
	return nil
}

type MongoError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          float32                `protobuf:"fixed32,1,opt,name=code,proto3" json:"code,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MongoError) Reset() {
	*x = MongoError{}
	mi := &file_mongo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MongoError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MongoError) ProtoMessage() {}

func (x *MongoError) ProtoReflect() protoreflect.Message {
	mi := &file_mongo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MongoError.ProtoReflect.Descriptor instead.
func (*MongoError) Descriptor() ([]byte, []int) {
	return file_mongo_proto_rawDescGZIP(), []int{5}
}

func (x *MongoError) GetCode() float32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MongoError) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type MongoErrors struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*MongoError          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	MachineType   string                 `protobuf:"bytes,2,opt,name=machineType,proto3" json:"machineType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MongoErrors) Reset() {
	*x = MongoErrors{}
	mi := &file_mongo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MongoErrors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MongoErrors) ProtoMessage() {}

func (x *MongoErrors) ProtoReflect() protoreflect.Message {
	mi := &file_mongo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MongoErrors.ProtoReflect.Descriptor instead.
func (*MongoErrors) Descriptor() ([]byte, []int) {
	return file_mongo_proto_rawDescGZIP(), []int{6}
}

func (x *MongoErrors) GetData() []*MongoError {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MongoErrors) GetMachineType() string {
	if x != nil {
		return x.MachineType
	}
	return ""
}

type MongoDataType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	CodeName      string                 `protobuf:"bytes,2,opt,name=codeName,proto3" json:"codeName,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=fullName,proto3" json:"fullName,omitempty"`
	Meaning       string                 `protobuf:"bytes,4,opt,name=meaning,proto3" json:"meaning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MongoDataType) Reset() {
	*x = MongoDataType{}
	mi := &file_mongo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MongoDataType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MongoDataType) ProtoMessage() {}

func (x *MongoDataType) ProtoReflect() protoreflect.Message {
	mi := &file_mongo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MongoDataType.ProtoReflect.Descriptor instead.
func (*MongoDataType) Descriptor() ([]byte, []int) {
	return file_mongo_proto_rawDescGZIP(), []int{7}
}

func (x *MongoDataType) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *MongoDataType) GetCodeName() string {
	if x != nil {
		return x.CodeName
	}
	return ""
}

func (x *MongoDataType) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *MongoDataType) GetMeaning() string {
	if x != nil {
		return x.Meaning
	}
	return ""
}

type MongoDataTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*MongoDataType       `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MongoDataTypes) Reset() {
	*x = MongoDataTypes{}
	mi := &file_mongo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MongoDataTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MongoDataTypes) ProtoMessage() {}

func (x *MongoDataTypes) ProtoReflect() protoreflect.Message {
	mi := &file_mongo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MongoDataTypes.ProtoReflect.Descriptor instead.
func (*MongoDataTypes) Descriptor() ([]byte, []int) {
	return file_mongo_proto_rawDescGZIP(), []int{8}
}

func (x *MongoDataTypes) GetData() []*MongoDataType {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_mongo_proto protoreflect.FileDescriptor

const file_mongo_proto_rawDesc = "" +
	"\n" +
	"\vmongo.proto\x12\tcybertele\x1a\vcyber.proto\"^\n" +
	"\fMongoRequest\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\tR\x02sn\x12 \n" +
	"\vmachineType\x18\x02 \x01(\tR\vmachineType\x12\x1c\n" +
	"\terrorCode\x18\x03 \x03(\x02R\terrorCode\"d\n" +
	"\x10MongoMachineType\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12(\n" +
	"\x0flocarusProtocol\x18\x03 \x01(\x05R\x0flocarusProtocol\"D\n" +
	"\x11MongoMachineTypes\x12/\n" +
	"\x04data\x18\x01 \x03(\v2\x1b.cybertele.MongoMachineTypeR\x04data\"\xa4\x01\n" +
	"\fMongoMachine\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\tR\x02sn\x12 \n" +
	"\vmachineType\x18\x02 \x01(\tR\vmachineType\x12\x12\n" +
	"\x04imei\x18\x03 \x01(\tR\x04imei\x12\x16\n" +
	"\x06status\x18\x04 \x01(\bR\x06status\x12\x18\n" +
	"\aexpDate\x18\x05 \x01(\tR\aexpDate\x12\x1c\n" +
	"\ttrackable\x18\x06 \x01(\bR\ttrackable\"<\n" +
	"\rMongoMachines\x12+\n" +
	"\x04data\x18\x01 \x03(\v2\x17.cybertele.MongoMachineR\x04data\"4\n" +
	"\n" +
	"MongoError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x02R\x04code\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"Z\n" +
	"\vMongoErrors\x12)\n" +
	"\x04data\x18\x01 \x03(\v2\x15.cybertele.MongoErrorR\x04data\x12 \n" +
	"\vmachineType\x18\x02 \x01(\tR\vmachineType\"w\n" +
	"\rMongoDataType\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x1a\n" +
	"\bcodeName\x18\x02 \x01(\tR\bcodeName\x12\x1a\n" +
	"\bfullName\x18\x03 \x01(\tR\bfullName\x12\x18\n" +
	"\ameaning\x18\x04 \x01(\tR\ameaning\">\n" +
	"\x0eMongoDataTypes\x12,\n" +
	"\x04data\x18\x01 \x03(\v2\x18.cybertele.MongoDataTypeR\x04data2\xdc\x02\n" +
	"\bMongoAux\x124\n" +
	"\x06Health\x12\x10.cybertele.Empty\x1a\x16.cybertele.HealthReply\"\x00\x12H\n" +
	"\x14GetMongoMachineTypes\x12\x10.cybertele.Empty\x1a\x1c.cybertele.MongoMachineTypes\"\x00\x12G\n" +
	"\x10GetMongoMachines\x12\x17.cybertele.MongoRequest\x1a\x18.cybertele.MongoMachines\"\x00\x12C\n" +
	"\x0eGetMongoErrors\x12\x17.cybertele.MongoRequest\x1a\x16.cybertele.MongoErrors\"\x00\x12B\n" +
	"\x11GetMongoDataTypes\x12\x10.cybertele.Empty\x1a\x19.cybertele.MongoDataTypes\"\x00B\tZ\a./protob\x06proto3"

var (
	file_mongo_proto_rawDescOnce sync.Once
	file_mongo_proto_rawDescData []byte
)

func file_mongo_proto_rawDescGZIP() []byte {
	file_mongo_proto_rawDescOnce.Do(func() {
		file_mongo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mongo_proto_rawDesc), len(file_mongo_proto_rawDesc)))
	})
	return file_mongo_proto_rawDescData
}

var file_mongo_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_mongo_proto_goTypes = []any{
	(*MongoRequest)(nil),      // 0: cybertele.MongoRequest
	(*MongoMachineType)(nil),  // 1: cybertele.MongoMachineType
	(*MongoMachineTypes)(nil), // 2: cybertele.MongoMachineTypes
	(*MongoMachine)(nil),      // 3: cybertele.MongoMachine
	(*MongoMachines)(nil),     // 4: cybertele.MongoMachines
	(*MongoError)(nil),        // 5: cybertele.MongoError
	(*MongoErrors)(nil),       // 6: cybertele.MongoErrors
	(*MongoDataType)(nil),     // 7: cybertele.MongoDataType
	(*MongoDataTypes)(nil),    // 8: cybertele.MongoDataTypes
	(*Empty)(nil),             // 9: cybertele.Empty
	(*HealthReply)(nil),       // 10: cybertele.HealthReply
}
var file_mongo_proto_depIdxs = []int32{
	1,  // 0: cybertele.MongoMachineTypes.data:type_name -> cybertele.MongoMachineType
	3,  // 1: cybertele.MongoMachines.data:type_name -> cybertele.MongoMachine
	5,  // 2: cybertele.MongoErrors.data:type_name -> cybertele.MongoError
	7,  // 3: cybertele.MongoDataTypes.data:type_name -> cybertele.MongoDataType
	9,  // 4: cybertele.MongoAux.Health:input_type -> cybertele.Empty
	9,  // 5: cybertele.MongoAux.GetMongoMachineTypes:input_type -> cybertele.Empty
	0,  // 6: cybertele.MongoAux.GetMongoMachines:input_type -> cybertele.MongoRequest
	0,  // 7: cybertele.MongoAux.GetMongoErrors:input_type -> cybertele.MongoRequest
	9,  // 8: cybertele.MongoAux.GetMongoDataTypes:input_type -> cybertele.Empty
	10, // 9: cybertele.MongoAux.Health:output_type -> cybertele.HealthReply
	2,  // 10: cybertele.MongoAux.GetMongoMachineTypes:output_type -> cybertele.MongoMachineTypes
	4,  // 11: cybertele.MongoAux.GetMongoMachines:output_type -> cybertele.MongoMachines
	6,  // 12: cybertele.MongoAux.GetMongoErrors:output_type -> cybertele.MongoErrors
	8,  // 13: cybertele.MongoAux.GetMongoDataTypes:output_type -> cybertele.MongoDataTypes
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_mongo_proto_init() }
func file_mongo_proto_init() {
	if File_mongo_proto != nil {
		return
	}
	file_cyber_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mongo_proto_rawDesc), len(file_mongo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mongo_proto_goTypes,
		DependencyIndexes: file_mongo_proto_depIdxs,
		MessageInfos:      file_mongo_proto_msgTypes,
	}.Build()
	File_mongo_proto = out.File
	file_mongo_proto_goTypes = nil
	file_mongo_proto_depIdxs = nil
}
