// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.12.4
// source: mongo.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MongoAux_Health_FullMethodName               = "/cybertele.MongoAux/Health"
	MongoAux_GetMongoMachineTypes_FullMethodName = "/cybertele.MongoAux/GetMongoMachineTypes"
	MongoAux_GetMongoMachines_FullMethodName     = "/cybertele.MongoAux/GetMongoMachines"
	MongoAux_GetMongoErrors_FullMethodName       = "/cybertele.MongoAux/GetMongoErrors"
	MongoAux_GetMongoDataTypes_FullMethodName    = "/cybertele.MongoAux/GetMongoDataTypes"
	MongoAux_GetMongoAllErrors_FullMethodName    = "/cybertele.MongoAux/GetMongoAllErrors"
)

// MongoAuxClient is the client API for MongoAux service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MongoAuxClient interface {
	Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthReply, error)
	GetMongoMachineTypes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MongoMachineTypes, error)
	GetMongoMachines(ctx context.Context, in *MongoRequest, opts ...grpc.CallOption) (*MongoMachines, error)
	GetMongoErrors(ctx context.Context, in *MongoRequest, opts ...grpc.CallOption) (*MongoErrors, error)
	GetMongoDataTypes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MongoDataTypes, error)
	GetMongoAllErrors(ctx context.Context, in *MongoRequest, opts ...grpc.CallOption) (*MongoErrors, error)
}

type mongoAuxClient struct {
	cc grpc.ClientConnInterface
}

func NewMongoAuxClient(cc grpc.ClientConnInterface) MongoAuxClient {
	return &mongoAuxClient{cc}
}

func (c *mongoAuxClient) Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthReply)
	err := c.cc.Invoke(ctx, MongoAux_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mongoAuxClient) GetMongoMachineTypes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MongoMachineTypes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MongoMachineTypes)
	err := c.cc.Invoke(ctx, MongoAux_GetMongoMachineTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mongoAuxClient) GetMongoMachines(ctx context.Context, in *MongoRequest, opts ...grpc.CallOption) (*MongoMachines, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MongoMachines)
	err := c.cc.Invoke(ctx, MongoAux_GetMongoMachines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mongoAuxClient) GetMongoErrors(ctx context.Context, in *MongoRequest, opts ...grpc.CallOption) (*MongoErrors, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MongoErrors)
	err := c.cc.Invoke(ctx, MongoAux_GetMongoErrors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mongoAuxClient) GetMongoDataTypes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MongoDataTypes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MongoDataTypes)
	err := c.cc.Invoke(ctx, MongoAux_GetMongoDataTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mongoAuxClient) GetMongoAllErrors(ctx context.Context, in *MongoRequest, opts ...grpc.CallOption) (*MongoErrors, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MongoErrors)
	err := c.cc.Invoke(ctx, MongoAux_GetMongoAllErrors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MongoAuxServer is the server API for MongoAux service.
// All implementations must embed UnimplementedMongoAuxServer
// for forward compatibility.
type MongoAuxServer interface {
	Health(context.Context, *Empty) (*HealthReply, error)
	GetMongoMachineTypes(context.Context, *Empty) (*MongoMachineTypes, error)
	GetMongoMachines(context.Context, *MongoRequest) (*MongoMachines, error)
	GetMongoErrors(context.Context, *MongoRequest) (*MongoErrors, error)
	GetMongoDataTypes(context.Context, *Empty) (*MongoDataTypes, error)
	GetMongoAllErrors(context.Context, *MongoRequest) (*MongoErrors, error)
	mustEmbedUnimplementedMongoAuxServer()
}

// UnimplementedMongoAuxServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMongoAuxServer struct{}

func (UnimplementedMongoAuxServer) Health(context.Context, *Empty) (*HealthReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedMongoAuxServer) GetMongoMachineTypes(context.Context, *Empty) (*MongoMachineTypes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMongoMachineTypes not implemented")
}
func (UnimplementedMongoAuxServer) GetMongoMachines(context.Context, *MongoRequest) (*MongoMachines, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMongoMachines not implemented")
}
func (UnimplementedMongoAuxServer) GetMongoErrors(context.Context, *MongoRequest) (*MongoErrors, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMongoErrors not implemented")
}
func (UnimplementedMongoAuxServer) GetMongoDataTypes(context.Context, *Empty) (*MongoDataTypes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMongoDataTypes not implemented")
}
func (UnimplementedMongoAuxServer) GetMongoAllErrors(context.Context, *MongoRequest) (*MongoErrors, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMongoAllErrors not implemented")
}
func (UnimplementedMongoAuxServer) mustEmbedUnimplementedMongoAuxServer() {}
func (UnimplementedMongoAuxServer) testEmbeddedByValue()                  {}

// UnsafeMongoAuxServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MongoAuxServer will
// result in compilation errors.
type UnsafeMongoAuxServer interface {
	mustEmbedUnimplementedMongoAuxServer()
}

func RegisterMongoAuxServer(s grpc.ServiceRegistrar, srv MongoAuxServer) {
	// If the following call panics, it indicates UnimplementedMongoAuxServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MongoAux_ServiceDesc, srv)
}

func _MongoAux_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoAuxServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MongoAux_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoAuxServer).Health(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MongoAux_GetMongoMachineTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoAuxServer).GetMongoMachineTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MongoAux_GetMongoMachineTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoAuxServer).GetMongoMachineTypes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MongoAux_GetMongoMachines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MongoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoAuxServer).GetMongoMachines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MongoAux_GetMongoMachines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoAuxServer).GetMongoMachines(ctx, req.(*MongoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MongoAux_GetMongoErrors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MongoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoAuxServer).GetMongoErrors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MongoAux_GetMongoErrors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoAuxServer).GetMongoErrors(ctx, req.(*MongoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MongoAux_GetMongoDataTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoAuxServer).GetMongoDataTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MongoAux_GetMongoDataTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoAuxServer).GetMongoDataTypes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MongoAux_GetMongoAllErrors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MongoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoAuxServer).GetMongoAllErrors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MongoAux_GetMongoAllErrors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoAuxServer).GetMongoAllErrors(ctx, req.(*MongoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MongoAux_ServiceDesc is the grpc.ServiceDesc for MongoAux service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MongoAux_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cybertele.MongoAux",
	HandlerType: (*MongoAuxServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _MongoAux_Health_Handler,
		},
		{
			MethodName: "GetMongoMachineTypes",
			Handler:    _MongoAux_GetMongoMachineTypes_Handler,
		},
		{
			MethodName: "GetMongoMachines",
			Handler:    _MongoAux_GetMongoMachines_Handler,
		},
		{
			MethodName: "GetMongoErrors",
			Handler:    _MongoAux_GetMongoErrors_Handler,
		},
		{
			MethodName: "GetMongoDataTypes",
			Handler:    _MongoAux_GetMongoDataTypes_Handler,
		},
		{
			MethodName: "GetMongoAllErrors",
			Handler:    _MongoAux_GetMongoAllErrors_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mongo.proto",
}
