# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import cyber_pb2 as cyber__pb2
import cybermetrica_pb2 as cybermetrica__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cybermetrica_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CybermetricaStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/cybertele.Cybermetrica/Health',
                request_serializer=cyber__pb2.Empty.SerializeToString,
                response_deserializer=cyber__pb2.HealthReply.FromString,
                _registered_method=True)
        self.StartParser = channel.unary_unary(
                '/cybertele.Cybermetrica/StartParser',
                request_serializer=cyber__pb2.Empty.SerializeToString,
                response_deserializer=cyber__pb2.ParserStatus.FromString,
                _registered_method=True)
        self.StopParser = channel.unary_unary(
                '/cybertele.Cybermetrica/StopParser',
                request_serializer=cyber__pb2.Empty.SerializeToString,
                response_deserializer=cyber__pb2.ParserStatus.FromString,
                _registered_method=True)
        self.MachineStatisticPeriod = channel.unary_unary(
                '/cybertele.Cybermetrica/MachineStatisticPeriod',
                request_serializer=cybermetrica__pb2.MachineStatisticRequest.SerializeToString,
                response_deserializer=cybermetrica__pb2.StatisticPeriod.FromString,
                _registered_method=True)
        self.GetTelemetryParams = channel.unary_unary(
                '/cybertele.Cybermetrica/GetTelemetryParams',
                request_serializer=cyber__pb2.Empty.SerializeToString,
                response_deserializer=cybermetrica__pb2.TelemertyParams.FromString,
                _registered_method=True)
        self.CreateTelemetryParam = channel.unary_unary(
                '/cybertele.Cybermetrica/CreateTelemetryParam',
                request_serializer=cybermetrica__pb2.TelemertyParam.SerializeToString,
                response_deserializer=cyber__pb2.StatusReply.FromString,
                _registered_method=True)
        self.UpdateTelemetryParam = channel.unary_unary(
                '/cybertele.Cybermetrica/UpdateTelemetryParam',
                request_serializer=cybermetrica__pb2.TelemertyParam.SerializeToString,
                response_deserializer=cyber__pb2.StatusReply.FromString,
                _registered_method=True)
        self.GetTimeline = channel.unary_unary(
                '/cybertele.Cybermetrica/GetTimeline',
                request_serializer=cybermetrica__pb2.TimelineRequest.SerializeToString,
                response_deserializer=cybermetrica__pb2.Timeline.FromString,
                _registered_method=True)


class CybermetricaServicer:
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """v1
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartParser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopParser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MachineStatisticPeriod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTelemetryParams(self, request, context):
        """v2
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTelemetryParam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTelemetryParam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTimeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CybermetricaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=cyber__pb2.Empty.FromString,
                    response_serializer=cyber__pb2.HealthReply.SerializeToString,
            ),
            'StartParser': grpc.unary_unary_rpc_method_handler(
                    servicer.StartParser,
                    request_deserializer=cyber__pb2.Empty.FromString,
                    response_serializer=cyber__pb2.ParserStatus.SerializeToString,
            ),
            'StopParser': grpc.unary_unary_rpc_method_handler(
                    servicer.StopParser,
                    request_deserializer=cyber__pb2.Empty.FromString,
                    response_serializer=cyber__pb2.ParserStatus.SerializeToString,
            ),
            'MachineStatisticPeriod': grpc.unary_unary_rpc_method_handler(
                    servicer.MachineStatisticPeriod,
                    request_deserializer=cybermetrica__pb2.MachineStatisticRequest.FromString,
                    response_serializer=cybermetrica__pb2.StatisticPeriod.SerializeToString,
            ),
            'GetTelemetryParams': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTelemetryParams,
                    request_deserializer=cyber__pb2.Empty.FromString,
                    response_serializer=cybermetrica__pb2.TelemertyParams.SerializeToString,
            ),
            'CreateTelemetryParam': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTelemetryParam,
                    request_deserializer=cybermetrica__pb2.TelemertyParam.FromString,
                    response_serializer=cyber__pb2.StatusReply.SerializeToString,
            ),
            'UpdateTelemetryParam': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTelemetryParam,
                    request_deserializer=cybermetrica__pb2.TelemertyParam.FromString,
                    response_serializer=cyber__pb2.StatusReply.SerializeToString,
            ),
            'GetTimeline': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTimeline,
                    request_deserializer=cybermetrica__pb2.TimelineRequest.FromString,
                    response_serializer=cybermetrica__pb2.Timeline.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cybertele.Cybermetrica', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cybertele.Cybermetrica', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Cybermetrica:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cybertele.Cybermetrica/Health',
            cyber__pb2.Empty.SerializeToString,
            cyber__pb2.HealthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartParser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cybertele.Cybermetrica/StartParser',
            cyber__pb2.Empty.SerializeToString,
            cyber__pb2.ParserStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopParser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cybertele.Cybermetrica/StopParser',
            cyber__pb2.Empty.SerializeToString,
            cyber__pb2.ParserStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MachineStatisticPeriod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cybertele.Cybermetrica/MachineStatisticPeriod',
            cybermetrica__pb2.MachineStatisticRequest.SerializeToString,
            cybermetrica__pb2.StatisticPeriod.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTelemetryParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cybertele.Cybermetrica/GetTelemetryParams',
            cyber__pb2.Empty.SerializeToString,
            cybermetrica__pb2.TelemertyParams.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTelemetryParam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cybertele.Cybermetrica/CreateTelemetryParam',
            cybermetrica__pb2.TelemertyParam.SerializeToString,
            cyber__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTelemetryParam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cybertele.Cybermetrica/UpdateTelemetryParam',
            cybermetrica__pb2.TelemertyParam.SerializeToString,
            cyber__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTimeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cybertele.Cybermetrica/GetTimeline',
            cybermetrica__pb2.TimelineRequest.SerializeToString,
            cybermetrica__pb2.Timeline.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
