# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import cyber_pb2 as cyber__pb2
import events_pb2 as events__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in events_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CybereventsStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/cybertele.Cyberevents/Health',
                request_serializer=cyber__pb2.Empty.SerializeToString,
                response_deserializer=cyber__pb2.HealthReply.FromString,
                _registered_method=True)
        self.SetEvents = channel.unary_unary(
                '/cybertele.Cyberevents/SetEvents',
                request_serializer=events__pb2.SetEventsRequest.SerializeToString,
                response_deserializer=cyber__pb2.StatusReply.FromString,
                _registered_method=True)
        self.GetMachineEvents = channel.unary_unary(
                '/cybertele.Cyberevents/GetMachineEvents',
                request_serializer=events__pb2.GetMachineEventsRequest.SerializeToString,
                response_deserializer=events__pb2.EventsReply.FromString,
                _registered_method=True)
        self.GetGroupEvents = channel.unary_unary(
                '/cybertele.Cyberevents/GetGroupEvents',
                request_serializer=events__pb2.GetGroupEventsRequest.SerializeToString,
                response_deserializer=events__pb2.EventsReply.FromString,
                _registered_method=True)


class CybereventsServicer:
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMachineEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroupEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CybereventsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=cyber__pb2.Empty.FromString,
                    response_serializer=cyber__pb2.HealthReply.SerializeToString,
            ),
            'SetEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.SetEvents,
                    request_deserializer=events__pb2.SetEventsRequest.FromString,
                    response_serializer=cyber__pb2.StatusReply.SerializeToString,
            ),
            'GetMachineEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMachineEvents,
                    request_deserializer=events__pb2.GetMachineEventsRequest.FromString,
                    response_serializer=events__pb2.EventsReply.SerializeToString,
            ),
            'GetGroupEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroupEvents,
                    request_deserializer=events__pb2.GetGroupEventsRequest.FromString,
                    response_serializer=events__pb2.EventsReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cybertele.Cyberevents', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cybertele.Cyberevents', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Cyberevents:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cybertele.Cyberevents/Health',
            cyber__pb2.Empty.SerializeToString,
            cyber__pb2.HealthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cybertele.Cyberevents/SetEvents',
            events__pb2.SetEventsRequest.SerializeToString,
            cyber__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMachineEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cybertele.Cyberevents/GetMachineEvents',
            events__pb2.GetMachineEventsRequest.SerializeToString,
            events__pb2.EventsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGroupEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cybertele.Cyberevents/GetGroupEvents',
            events__pb2.GetGroupEventsRequest.SerializeToString,
            events__pb2.EventsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
