# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import cyber_pb2 as cyber__pb2
import maintenance_pb2 as maintenance__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in maintenance_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MaintenanceForecastStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/cybertele.MaintenanceForecast/Health',
                request_serializer=cyber__pb2.Empty.SerializeToString,
                response_deserializer=cyber__pb2.HealthReply.FromString,
                _registered_method=True)
        self.GetForecast = channel.unary_unary(
                '/cybertele.MaintenanceForecast/GetForecast',
                request_serializer=maintenance__pb2.ForecastRequest.SerializeToString,
                response_deserializer=maintenance__pb2.ForecastReply.FromString,
                _registered_method=True)
        self.BuildForecast = channel.unary_unary(
                '/cybertele.MaintenanceForecast/BuildForecast',
                request_serializer=maintenance__pb2.ForecastRequest.SerializeToString,
                response_deserializer=maintenance__pb2.ForecastReply.FromString,
                _registered_method=True)
        self.GetMahineForecasts = channel.unary_unary(
                '/cybertele.MaintenanceForecast/GetMahineForecasts',
                request_serializer=maintenance__pb2.ForecastRequest.SerializeToString,
                response_deserializer=maintenance__pb2.ForecastReply.FromString,
                _registered_method=True)


class MaintenanceForecastServicer:
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetForecast(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuildForecast(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMahineForecasts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MaintenanceForecastServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=cyber__pb2.Empty.FromString,
                    response_serializer=cyber__pb2.HealthReply.SerializeToString,
            ),
            'GetForecast': grpc.unary_unary_rpc_method_handler(
                    servicer.GetForecast,
                    request_deserializer=maintenance__pb2.ForecastRequest.FromString,
                    response_serializer=maintenance__pb2.ForecastReply.SerializeToString,
            ),
            'BuildForecast': grpc.unary_unary_rpc_method_handler(
                    servicer.BuildForecast,
                    request_deserializer=maintenance__pb2.ForecastRequest.FromString,
                    response_serializer=maintenance__pb2.ForecastReply.SerializeToString,
            ),
            'GetMahineForecasts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMahineForecasts,
                    request_deserializer=maintenance__pb2.ForecastRequest.FromString,
                    response_serializer=maintenance__pb2.ForecastReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cybertele.MaintenanceForecast', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cybertele.MaintenanceForecast', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MaintenanceForecast:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cybertele.MaintenanceForecast/Health',
            cyber__pb2.Empty.SerializeToString,
            cyber__pb2.HealthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetForecast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cybertele.MaintenanceForecast/GetForecast',
            maintenance__pb2.ForecastRequest.SerializeToString,
            maintenance__pb2.ForecastReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuildForecast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cybertele.MaintenanceForecast/BuildForecast',
            maintenance__pb2.ForecastRequest.SerializeToString,
            maintenance__pb2.ForecastReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMahineForecasts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cybertele.MaintenanceForecast/GetMahineForecasts',
            maintenance__pb2.ForecastRequest.SerializeToString,
            maintenance__pb2.ForecastReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
