# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: maintenance.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'maintenance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import cyber_pb2 as cyber__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11maintenance.proto\x12\tcybertele\x1a\x0b\x63yber.proto\"+\n\x0f\x46orecastRequest\x12\n\n\x02sn\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\"+\n\x0c\x46orecastItem\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\"\xac\x01\n\rForecastReply\x12\n\n\x02sn\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12(\n\x07history\x18\x03 \x03(\x0b\x32\x17.cybertele.ForecastItem\x12)\n\x08\x66orecast\x18\x04 \x03(\x0b\x32\x17.cybertele.ForecastItem\x12,\n\x0bmaintenance\x18\x05 \x03(\x0b\x32\x17.cybertele.ForecastItem\"=\n\x0e\x46orecastsReply\x12+\n\tforecasts\x18\x01 \x03(\x0b\x32\x18.cybertele.ForecastReply2\xaa\x02\n\x13MaintenanceForecast\x12\x34\n\x06Health\x12\x10.cybertele.Empty\x1a\x16.cybertele.HealthReply\"\x00\x12\x45\n\x0bGetForecast\x12\x1a.cybertele.ForecastRequest\x1a\x18.cybertele.ForecastReply\"\x00\x12G\n\rBuildForecast\x12\x1a.cybertele.ForecastRequest\x1a\x18.cybertele.ForecastReply\"\x00\x12M\n\x12GetMahineForecasts\x12\x1a.cybertele.ForecastRequest\x1a\x19.cybertele.ForecastsReply\"\x00\x42\tZ\x07./protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'maintenance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007./proto'
  _globals['_FORECASTREQUEST']._serialized_start=45
  _globals['_FORECASTREQUEST']._serialized_end=88
  _globals['_FORECASTITEM']._serialized_start=90
  _globals['_FORECASTITEM']._serialized_end=133
  _globals['_FORECASTREPLY']._serialized_start=136
  _globals['_FORECASTREPLY']._serialized_end=308
  _globals['_FORECASTSREPLY']._serialized_start=310
  _globals['_FORECASTSREPLY']._serialized_end=371
  _globals['_MAINTENANCEFORECAST']._serialized_start=374
  _globals['_MAINTENANCEFORECAST']._serialized_end=672
# @@protoc_insertion_point(module_scope)
