# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import cyber_pb2 as cyber__pb2
import mongo_pb2 as mongo__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mongo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MongoAuxStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/cybertele.MongoAux/Health',
                request_serializer=cyber__pb2.Empty.SerializeToString,
                response_deserializer=cyber__pb2.HealthReply.FromString,
                _registered_method=True)
        self.GetMongoMachineTypes = channel.unary_unary(
                '/cybertele.MongoAux/GetMongoMachineTypes',
                request_serializer=cyber__pb2.Empty.SerializeToString,
                response_deserializer=mongo__pb2.MongoMachineTypes.FromString,
                _registered_method=True)
        self.GetMongoMachines = channel.unary_unary(
                '/cybertele.MongoAux/GetMongoMachines',
                request_serializer=mongo__pb2.MongoRequest.SerializeToString,
                response_deserializer=mongo__pb2.MongoMachines.FromString,
                _registered_method=True)
        self.GetMongoErrors = channel.unary_unary(
                '/cybertele.MongoAux/GetMongoErrors',
                request_serializer=mongo__pb2.MongoRequest.SerializeToString,
                response_deserializer=mongo__pb2.MongoErrors.FromString,
                _registered_method=True)
        self.GetMongoDataTypes = channel.unary_unary(
                '/cybertele.MongoAux/GetMongoDataTypes',
                request_serializer=cyber__pb2.Empty.SerializeToString,
                response_deserializer=mongo__pb2.MongoDataTypes.FromString,
                _registered_method=True)
        self.GetMongoAllErrors = channel.unary_unary(
                '/cybertele.MongoAux/GetMongoAllErrors',
                request_serializer=mongo__pb2.MongoRequest.SerializeToString,
                response_deserializer=mongo__pb2.MongoErrors.FromString,
                _registered_method=True)


class MongoAuxServicer:
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMongoMachineTypes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMongoMachines(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMongoErrors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMongoDataTypes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMongoAllErrors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MongoAuxServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=cyber__pb2.Empty.FromString,
                    response_serializer=cyber__pb2.HealthReply.SerializeToString,
            ),
            'GetMongoMachineTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMongoMachineTypes,
                    request_deserializer=cyber__pb2.Empty.FromString,
                    response_serializer=mongo__pb2.MongoMachineTypes.SerializeToString,
            ),
            'GetMongoMachines': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMongoMachines,
                    request_deserializer=mongo__pb2.MongoRequest.FromString,
                    response_serializer=mongo__pb2.MongoMachines.SerializeToString,
            ),
            'GetMongoErrors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMongoErrors,
                    request_deserializer=mongo__pb2.MongoRequest.FromString,
                    response_serializer=mongo__pb2.MongoErrors.SerializeToString,
            ),
            'GetMongoDataTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMongoDataTypes,
                    request_deserializer=cyber__pb2.Empty.FromString,
                    response_serializer=mongo__pb2.MongoDataTypes.SerializeToString,
            ),
            'GetMongoAllErrors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMongoAllErrors,
                    request_deserializer=mongo__pb2.MongoRequest.FromString,
                    response_serializer=mongo__pb2.MongoErrors.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cybertele.MongoAux', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cybertele.MongoAux', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MongoAux:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cybertele.MongoAux/Health',
            cyber__pb2.Empty.SerializeToString,
            cyber__pb2.HealthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMongoMachineTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cybertele.MongoAux/GetMongoMachineTypes',
            cyber__pb2.Empty.SerializeToString,
            mongo__pb2.MongoMachineTypes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMongoMachines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cybertele.MongoAux/GetMongoMachines',
            mongo__pb2.MongoRequest.SerializeToString,
            mongo__pb2.MongoMachines.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMongoErrors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cybertele.MongoAux/GetMongoErrors',
            mongo__pb2.MongoRequest.SerializeToString,
            mongo__pb2.MongoErrors.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMongoDataTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cybertele.MongoAux/GetMongoDataTypes',
            cyber__pb2.Empty.SerializeToString,
            mongo__pb2.MongoDataTypes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMongoAllErrors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cybertele.MongoAux/GetMongoAllErrors',
            mongo__pb2.MongoRequest.SerializeToString,
            mongo__pb2.MongoErrors.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
